### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by xj361685640** [czyt1988/SARibbon#1]
VS2013+QT5.7.0和 VS2017+QT5.9.3均编译失败，请问您用的是什么环境
我的错误如下
1>------ 已启动生成:  项目: SARibbonBar, 配置: Release x64 ------
1>  Moc'ing FramelessHelper.h...
1>  Moc'ing SARibbonApplicationButton.h...
1>  Moc'ing SARibbonBar.h...
1>  Moc'ing SARibbonCategory.h...
1>  Moc'ing SARibbonComboBox.h...
1>  Moc'ing SARibbonContextCategory.h...
1>  Moc'ing SARibbonControlButton.h...
1>  Moc'ing SARibbonGallery.h...
1>  Moc'ing SARibbonGalleryGroup.h...
1>  Moc'ing SARibbonLineEdit.h...
1>  Moc'ing SARibbonMainWindow.h...
1>  Moc'ing SARibbonMenu.h...
1>  Moc'ing SARibbonPannel.h...
1>  Moc'ing SARibbonPannelOptionButton.h...
1>  Moc'ing SARibbonStackedWidget.h...
1>  Moc'ing SARibbonTabBar.h...
1>  Moc'ing SARibbonToolButton.h...
1>  Moc'ing SAWindowButtonGroup.h...
1>  Rcc'ing resource.qrc...
1>  FramelessHelper.cpp
1>FramelessHelper.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\FramelessHelper.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  moc_FramelessHelper.cpp
1>c:\users\administrator\desktop\saribbon-master\src\release\../FramelessHelper.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  moc_SARibbonApplicationButton.cpp
1>  moc_SARibbonBar.cpp
1>c:\users\administrator\desktop\saribbon-master\src\release\../SARibbonBar.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  moc_SARibbonCategory.cpp
1>c:\users\administrator\desktop\saribbon-master\src\release\../SARibbonCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  moc_SARibbonComboBox.cpp
1>c:\users\administrator\desktop\saribbon-master\src\release\../SARibbonComboBox.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  moc_SARibbonContextCategory.cpp
1>c:\users\administrator\desktop\saribbon-master\src\release\../SARibbonContextCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  moc_SARibbonControlButton.cpp
1>  moc_SARibbonGallery.cpp
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryGroup.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryItem.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  moc_SARibbonGalleryGroup.cpp
1>c:\users\administrator\desktop\saribbon-master\src\release\../SARibbonGalleryGroup.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryItem.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  moc_SARibbonLineEdit.cpp
1>  moc_SARibbonMainWindow.cpp
1>c:\users\administrator\desktop\saribbon-master\src\release\../SARibbonMainWindow.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  moc_SARibbonMenu.cpp
1>  moc_SARibbonPannel.cpp
1>  moc_SARibbonPannelOptionButton.cpp
1>c:\users\administrator\desktop\saribbon-master\src\release\../SARibbonPannelOptionButton.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  moc_SARibbonStackedWidget.cpp
1>  moc_SARibbonTabBar.cpp
1>  moc_SARibbonToolButton.cpp
1>  moc_SAWindowButtonGroup.cpp
1>  SARibbonApplicationButton.cpp
1>  正在生成代码...
1>  正在编译...
1>  SARibbonBar.cpp
1>SARibbonBar.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonBar.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonElementCreateDelegate.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>SARibbonBar.cpp(195): error C2039: “setContextColor”: 不是“SARibbonContextCategory”的成员
1>          c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h(9) : 参见“SARibbonContextCategory”的声明
1>SARibbonBar.cpp(212): error C2039: “categoryCount”: 不是“SARibbonContextCategory”的成员
1>          c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h(9) : 参见“SARibbonContextCategory”的声明
1>SARibbonBar.cpp(214): error C2039: “categoryPage”: 不是“SARibbonContextCategory”的成员
1>          c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h(9) : 参见“SARibbonContextCategory”的声明
1>SARibbonBar.cpp(287): error C2039: “createHidePannelButton”: 不是“SARibbonElementCreateDelegate”的成员
1>          c:\users\administrator\desktop\saribbon-master\src\SARibbonElementCreateDelegate.h(21) : 参见“SARibbonElementCreateDelegate”的声明
1>  SARibbonButtonGroupWidget.cpp
1>  SARibbonCategory.cpp
1>SARibbonCategory.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonSeparatorWidget.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonElementCreateDelegate.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  SARibbonCategoryLayout.cpp
1>SARibbonCategoryLayout.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>SARibbonCategoryLayout.cpp(122): warning C4100: “watched”: 未引用的形参
1>SARibbonCategoryLayout.cpp(279): error C2065: “j”: 未声明的标识符
1>SARibbonCategoryLayout.cpp(279): error C2228: “.second”的左边必须有类/结构/联合
1>SARibbonCategoryLayout.cpp(279): error C2228: “.adjust”的左边必须有类/结构/联合
1>  SARibbonCheckBox.cpp
1>  SARibbonComboBox.cpp
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonComboBox.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  SARibbonContextCategory.cpp
1>SARibbonContextCategory.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonElementCreateDelegate.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>SARibbonContextCategory.cpp(30): error C2039: “addCategoryPage”: 不是“SARibbonContextCategory”的成员
1>          c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h(9) : 参见“SARibbonContextCategory”的声明
1>SARibbonContextCategory.cpp(33): error C3861: “parentWidget”:  找不到标识符
1>SARibbonContextCategory.cpp(36): error C2065: “m_d”: 未声明的标识符
1>SARibbonContextCategory.cpp(36): error C2227: “->categoryDataList”的左边必须指向类/结构/联合/泛型类型
1>          类型是“unknown-type”
1>SARibbonContextCategory.cpp(36): error C2228: “.append”的左边必须有类/结构/联合
1>SARibbonContextCategory.cpp(37): error C3861: “categoryPageAdded”:  找不到标识符
1>SARibbonContextCategory.cpp(41): error C2039: “categoryCount”: 不是“SARibbonContextCategory”的成员
1>          c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h(9) : 参见“SARibbonContextCategory”的声明
1>SARibbonContextCategory.cpp(42): error C2270: “categoryCount”: 非成员函数上不允许修饰符
1>SARibbonContextCategory.cpp(43): error C2065: “m_d”: 未声明的标识符
1>SARibbonContextCategory.cpp(43): error C2227: “->categoryDataList”的左边必须指向类/结构/联合/泛型类型
1>          类型是“unknown-type”
1>SARibbonContextCategory.cpp(43): error C2228: “.count”的左边必须有类/结构/联合
1>SARibbonContextCategory.cpp(56): error C2039: “setContextColor”: 不是“SARibbonContextCategory”的成员
1>          c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h(9) : 参见“SARibbonContextCategory”的声明
1>SARibbonContextCategory.cpp(58): error C2065: “m_d”: 未声明的标识符
1>SARibbonContextCategory.cpp(58): error C2227: “->contextColor”的左边必须指向类/结构/联合/泛型类型
1>          类型是“unknown-type”
1>SARibbonContextCategory.cpp(84): error C2039: “categoryPage”: 不是“SARibbonContextCategory”的成员
1>          c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h(9) : 参见“SARibbonContextCategory”的声明
1>SARibbonContextCategory.cpp(86): error C2065: “m_d”: 未声明的标识符
1>SARibbonContextCategory.cpp(86): error C2227: “->categoryDataList”的左边必须指向类/结构/联合/泛型类型
1>          类型是“unknown-type”
1>SARibbonContextCategory.cpp(86): error C2228: “.categoryPage”的左边必须有类/结构/联合
1>  SARibbonControlButton.cpp
1>  SARibbonCtrolContainer.cpp
1>  SARibbonDrawHelper.cpp
1>  SARibbonElementCreateDelegate.cpp
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonElementCreateDelegate.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonBar.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonSeparatorWidget.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryGroup.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryItem.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>SARibbonElementCreateDelegate.cpp(75): error C2039: “createHidePannelButton”: 不是“SARibbonElementCreateDelegate”的成员
1>          c:\users\administrator\desktop\saribbon-master\src\SARibbonElementCreateDelegate.h(21) : 参见“SARibbonElementCreateDelegate”的声明
1>  SARibbonElementManager.cpp
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonElementCreateDelegate.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  SARibbonGallery.cpp
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryGroup.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryItem.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonElementCreateDelegate.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  SARibbonGalleryGroup.cpp
1>SARibbonGalleryGroup.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryGroup.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryItem.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  SARibbonGalleryItem.cpp
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryItem.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryGroup.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  SARibbonLineEdit.cpp
1>  SARibbonMainWindow.cpp
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonMainWindow.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\FramelessHelper.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonBar.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonContextCategory.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  SARibbonMenu.cpp
1>  SARibbonPannel.cpp
1>SARibbonPannel.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonPannelOptionButton.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonSeparatorWidget.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryGroup.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonGalleryItem.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonElementCreateDelegate.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>SARibbonPannel.cpp(40): error C2614: “SARibbonPannelPrivate”: 非法的成员初始化:“m_titleY”不是基或成员
1>SARibbonPannel.cpp(290): error C2039: “connectAction”: 不是“SARibbonPannelOptionButton”的成员
1>          c:\users\administrator\desktop\saribbon-master\src\SARibbonPannelOptionButton.h(6) : 参见“SARibbonPannelOptionButton”的声明
1>SARibbonPannel.cpp(313): error C2039: “m_titleY”: 不是“SARibbonPannelPrivate”的成员
1>          SARibbonPannel.cpp(18) : 参见“SARibbonPannelPrivate”的声明
1>SARibbonPannel.cpp(314): error C2661: “QPainter::drawText”: 没有重载函数接受 5 个参数
1>SARibbonPannel.cpp(318): error C2039: “m_titleY”: 不是“SARibbonPannelPrivate”的成员
1>          SARibbonPannel.cpp(18) : 参见“SARibbonPannelPrivate”的声明
1>SARibbonPannel.cpp(318): error C2661: “QPainter::drawText”: 没有重载函数接受 5 个参数
1>SARibbonPannel.cpp(378): error C2039: “m_titleY”: 不是“SARibbonPannelPrivate”的成员
1>          SARibbonPannel.cpp(18) : 参见“SARibbonPannelPrivate”的声明
1>SARibbonPannel.cpp(378): error C2664: “void QWidget::move(const QPoint &)”: 无法将参数 1 从“int”转换为“const QPoint &”
1>          原因如下:  无法从“int”转换为“const QPoint”
1>          无构造函数可以接受源类型，或构造函数重载决策不明确
1>  SARibbonPannelOptionButton.cpp
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonPannelOptionButton.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>SARibbonPannelOptionButton.cpp(14): error C2039: “connectAction”: 不是“SARibbonPannelOptionButton”的成员
1>          c:\users\administrator\desktop\saribbon-master\src\SARibbonPannelOptionButton.h(6) : 参见“SARibbonPannelOptionButton”的声明
1>SARibbonPannelOptionButton.cpp(16): error C2355: “this”: 只能在非静态成员函数或非静态数据成员初始值设定项的内部引用
1>SARibbonPannelOptionButton.cpp(16): error C3861: “connect”:  找不到标识符
1>  正在生成代码...
1>  正在编译...
1>  SARibbonQuickAccessBar.cpp
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonSeparatorWidget.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  SARibbonSeparatorWidget.cpp
1>c:\users\administrator\desktop\saribbon-master\src\SARibbonSeparatorWidget.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  SARibbonStackedWidget.cpp
1>  SARibbonTabBar.cpp
1>  SARibbonToolButton.cpp
1>SARibbonToolButton.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>SARibbonToolButton.cpp(183): error C2181: 没有匹配 if 的非法 else
1>SARibbonToolButton.cpp(200): error C2059: 语法错误:“else”
1>SARibbonToolButton.cpp(203): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>SARibbonToolButton.cpp(203): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>SARibbonToolButton.cpp(215): error C2059: 语法错误:“else”
1>SARibbonToolButton.cpp(216): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>SARibbonToolButton.cpp(216): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>SARibbonToolButton.cpp(234): error C2059: 语法错误:“if”
1>SARibbonToolButton.cpp(237): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>SARibbonToolButton.cpp(237): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>SARibbonToolButton.cpp(244): error C2065: “p”: 未声明的标识符
1>SARibbonToolButton.cpp(244): error C2065: “opt”: 未声明的标识符
1>SARibbonToolButton.cpp(244): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>SARibbonToolButton.cpp(244): error C2078: 初始值设定项太多
1>SARibbonToolButton.cpp(246): error C2059: 语法错误:“}”
1>SARibbonToolButton.cpp(246): error C2143: 语法错误 : 缺少“;”(在“}”的前面)
1>SARibbonToolButton.cpp(249): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>SARibbonToolButton.cpp(249): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>SARibbonToolButton.cpp(329): error C2059: 语法错误:“else”
1>SARibbonToolButton.cpp(332): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>SARibbonToolButton.cpp(332): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>SARibbonToolButton.cpp(344): error C2059: 语法错误:“else”
1>SARibbonToolButton.cpp(345): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>SARibbonToolButton.cpp(345): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>SARibbonToolButton.cpp(365): error C2059: 语法错误:“if”
1>SARibbonToolButton.cpp(368): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>SARibbonToolButton.cpp(368): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>SARibbonToolButton.cpp(378): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>SARibbonToolButton.cpp(396): error C2065: “p”: 未声明的标识符
1>SARibbonToolButton.cpp(396): error C2065: “opt”: 未声明的标识符
1>SARibbonToolButton.cpp(396): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>SARibbonToolButton.cpp(396): error C2374: “drawIconAndLabel”: 重定义；多次初始化
1>          SARibbonToolButton.cpp(244) : 参见“drawIconAndLabel”的声明
1>SARibbonToolButton.cpp(396): error C2078: 初始值设定项太多
1>SARibbonToolButton.cpp(397): error C2059: 语法错误:“}”
1>SARibbonToolButton.cpp(397): error C2143: 语法错误 : 缺少“;”(在“}”的前面)
1>SARibbonToolButton.cpp(400): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>SARibbonToolButton.cpp(400): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>SARibbonToolButton.cpp(412): error C2065: “label”: 未声明的标识符
1>SARibbonToolButton.cpp(412): error C2228: “.state”的左边必须有类/结构/联合
1>          类型是“unknown-type”
1>SARibbonToolButton.cpp(413): error C2065: “label”: 未声明的标识符
1>  SAWindowButtonGroup.cpp
1>SAWindowButtonGroup.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>  正在生成代码...
========== 生成:  成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by czyt1988** [comment]
MinGW的Qt5.7，我看主要是编码问题，vs对不带bom的UTF-8编码支持不好，里面的中文会解析成乱码，我用vs版编译一下看看。或许要把所有转换为带bom的UTF-8才行

**Comment by xj361685640** [comment]
谢谢您的提醒，我已经修改编码格式重新编译成功了。

**Comment by czyt1988** [comment]
感谢意见，我重新改了编码，同时调整了一下结构，MinGW Qt5.7和MSVC2010 Qt5.5都编译通过了
@xj361685640

**Comment by xj361685640** [comment]
我已经测试，可以运行，谢谢！
