### ISSUE TITLE
SARibbonBar布局議題

### ISSUE THREAD

**Issue by timpc0526** [czyt1988/SARibbon#107]
您好，在嘗試將各種item用於Bar上，發現想要實現QLabel加上widget會出現問題，在addLargeWidget正常顯示，然而在addMediumWidget以及addSmallWidget會出現顯示問題，不知是否有什麼地方出現錯誤，感謝您。
`QLabel* label_gridRow = new QLabel();`
`label_gridRow->setText("Row");`
`SARibbonLineEdit* lineEdit_gridRow = new SARibbonLineEdit();`
`QWidget* widget_gridRow = new QWidget();`
`QHBoxLayout* layout_gridRow = new QHBoxLayout;`
`layout_gridRow->addWidget(label_gridRow);`
`layout_gridRow->addWidget(lineEdit_gridRow);`
`widget_gridRow->setLayout(layout_gridRow);`
`pannelStyleMethod->addLargeWidget(widget_gridRow);`
![SARibbonBarIssue](https://github.com/czyt1988/SARibbon/assets/68679458/eb911514-1dec-427c-89ef-c864d262d702)

**Comment by czyt1988** [comment]
我试了放入grid并没有问题啊

```c++
    // pannel 3
    pannel          = new SARibbonPannel(tr("Grid"));
    QWidget* w      = new QWidget();
    QGridLayout* g  = new QGridLayout(w);
    QLabel* lab1    = new QLabel("value1:");
    QLineEdit* edi1 = new QLineEdit(w);
    QLabel* lab2    = new QLabel("value2:");
    QLineEdit* edi2 = new QLineEdit(w);
    g->addWidget(lab1, 0, 0);
    g->addWidget(edi1, 0, 1);
    g->addWidget(lab2, 1, 0);
    g->addWidget(edi2, 1, 1);
    pannel->addLargeWidget(w);
    page->addPannel(pannel);
```

**Comment by czyt1988** [comment]
![image](https://github.com/czyt1988/SARibbon/assets/7260393/9ed96f6c-16e0-4c0f-b4cf-79396fb19b43)

**Comment by timpc0526** [comment]
非常感謝您的回覆 使用QGridLayout是可以使用的
目前遇到另一個議題想借用此串進行詢問
針對語言的轉換看到您的demo是使用connect對文字進行切換
若想要使用QLinguist進行翻譯 
SARibbonCategory 跟 SARibbonContextCategory並沒有類似setText的函數來更改名稱
導致無法切換語言

**Comment by czyt1988** [comment]
下面这些接口就是用来设置名称
```cpp
SARibbonCategory::setCategoryName
SARibbonPannel::setPannelName
SARibbonContextCategory::setContextTitle
```
