### ISSUE TITLE
请问SARibbonMainWindow 右上角的最大化、最小化、关闭三个按钮如何去掉或隐藏呢？

### ISSUE THREAD

**Issue by zhangweidi** [czyt1988/SARibbon#108]
我想让右上角的最大化、最小化、关闭三个按钮消失，我尝试设置 setWindowFlags(windowFlags() & ~Qt::WindowCloseButtonHint & ~Qt::WindowMinMaxButtonsHint); 但没有任何效果，请问如何解决呢？谢谢！

**Comment by czyt1988** [comment]
SARibbonMainWindow::updateWindowFlag(Qt::WindowFlags flags);
