### ISSUE TITLE
SARibbonCategory中添加SARibbonPannel，然后再SARibbonPannel中添加QAction，名称过长无法自适应QAction的宽度

### ISSUE THREAD

**Issue by Backstree** [czyt1988/SARibbon#114]
SARibbonCategory中添加SARibbonPannel，然后再SARibbonPannel中添加QAction，名称过长无法自适应QAction的宽度。

![image](https://github.com/czyt1988/SARibbon/assets/38172057/124ff72b-164d-48e2-b533-c97b1ecfa85c)

点击SARibbonPannel中的任意QAction后，SARibbonPannel会自适应宽度，有没有可手动自适应的api？

![image](https://github.com/czyt1988/SARibbon/assets/38172057/5c7cf8f1-9a64-4584-adc4-401a41045820)

**Comment by czyt1988** [comment]
这个在v2.0.3+版本应该修复了，你当前是什么版本

**Comment by Backstree** [comment]
好的，我下载新版本试试，我使用的是1.06
