### ISSUE TITLE
SystemButton最大化按钮Windows11特性显示位置偏下方

### ISSUE THREAD

**Issue by emc2-2022** [czyt1988/SARibbon#119]
如图，Windows11特性显示位置偏下，鼠标移动慢将会导致提示超时隐藏。

![image](https://github.com/czyt1988/SARibbon/assets/10685686/c95a23ec-52c3-4b28-a625-b464ec93d60f)

附：Office Word效果：

![image](https://github.com/czyt1988/SARibbon/assets/10685686/56d396f8-fd1c-4cf0-b46c-1bd4eb5d276e)

**Comment by czyt1988** [comment]
此问题和qt版本有关，目前这个主要通过qwk来实现，不同版本qt有不同表现，可以通过cmake取消snap layout功能
