### ISSUE TITLE
bug-report: 面板和tabbar分离了, 还有tabbar的双击和单击没有作区分?

### ISSUE THREAD

**Issue by XIE-Yao** [czyt1988/SARibbon#16]
![图像 7](https://user-images.githubusercontent.com/46967601/103649336-4029bd80-4f99-11eb-8794-62f3e8dfe211.png)

首先收起面板, 然后挪动窗体, 再双击tab按钮, 这时候面板和窗体就分离了.

**Comment by XIE-Yao** [comment]
图片怎么发不出来呢?

**Comment by czyt1988** [comment]
这个问题了解，正在排查发自我的华为手机-------- 原始邮件 --------发件人： XIE-Yao <notifications@github.com>日期： 2021年1月5日周二 晚上9:03收件人： czyt1988/SARibbon <SARibbon@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [czyt1988/SARibbon] bug-report: 面板和tabbar分离了, 还有tabbar的双击和单击没有作区分? (#16)

图片怎么发不出来呢?

**Comment by czyt1988** [comment]
已经解决
