### ISSUE TITLE
Changing border color of a toolbutton

### ISSUE THREAD

**Issue by yanis60** [czyt1988/SARibbon#18]
Hi,
I have two themes (normal and dark), i need for each theme changing the toolbutton border color menu for example for a dark mode i want to make it white, but i can't tell to the ribbon that i'm in dark theme.

Can you please ad a function that returns the theme from the ribbon?

Thank you

**Comment by czyt1988** [comment]
Hello:

This problem has been solved in the latest version, but it should be noted that when setting QSS, the background color of SARibbonToolButton should not be set to transparent, which will affect the display effect in MenuButtonPopup mode

> 你好：
    此问题已经在最新版本中解决，不过需要注意的是，在设置qss时，SARibbonToolButton的background-color不要设置为transparent，这样会影响MenuButtonPopup模式下的显示效果
