### ISSUE TITLE
MSVC2017 编译不过

### ISSUE THREAD

**Issue by HlKun** [czyt1988/SARibbon#20]
是不适用与MSVC2017吗？

**Comment by czyt1988** [comment]
错误信息是什么，理论都可以发自我的华为手机-------- 原始邮件 --------发件人： HlKun ***@***.***>日期： 2021年4月8日周四 傍晚5:12收件人： czyt1988/SARibbon ***@***.***>抄送： Subscribed ***@***.***>主    题： [czyt1988/SARibbon] MSVC2017 编译不过 (#20)

是不适用与MSVC2017吗？

**Comment by HlKun** [comment]
MSVC2017 32bit 编译的错误（MSVC2017 64bit编译错误一样）
![image](https://user-images.githubusercontent.com/46489569/114116561-7f103c00-9917-11eb-8e03-4209e34c8e88.png)

但是用MinGW编译就没问题

**Comment by czyt1988** [comment]
编码问题，vs是带bom的utf-8，可以通过qt设置带bom的utf-8，然后转换一下编码发自我的华为手机-------- 原始邮件 --------发件人： HlKun ***@***.***>日期： 2021年4月9日周五 上午9:41收件人： czyt1988/SARibbon ***@***.***>抄送： czy ***@***.***>, Comment ***@***.***>主    题： Re: [czyt1988/SARibbon] MSVC2017 编译不过 (#20)

MSVC2017 32bit 编译的错误（MSVC2017 64bit编译错误一样）



但是用MinGW编译就没问题

**Comment by MrLiuSheng** [comment]
使用MSVC2015 64bit 遇到同样的问题，
![image](https://user-images.githubusercontent.com/73326699/124746751-cd9f9780-df53-11eb-8e09-e9d78019e04f.png)
，设置转码一样不行

**Comment by czyt1988** [comment]
> 使用MSVC2015 64bit 遇到同样的问题，
> ![image](https://user-images.githubusercontent.com/73326699/124746751-cd9f9780-df53-11eb-8e09-e9d78019e04f.png)
> ，设置转码一样不行

原来的编码要转换一下，最新的分支理论都可以，我vs2017是没问题，有问题就找个软件把所有编码转换为带bom的，没有软件就随便敲个空格用qt creator保存

**Comment by MrLiuSheng** [comment]
测试环境：Based on Qt 5.13.1 +MSVC2015 64bit
编译运行通过，需要把所有的文件编码转为UTF-8 BOM就行了
感谢！



***@***.***
 
发件人： czy
发送时间： 2021-07-11 13:49
收件人： czyt1988/SARibbon
抄送： MrLiuSheng; Comment
主题： Re: [czyt1988/SARibbon] MSVC2017 编译不过 (#20)
使用MSVC2015 64bit 遇到同样的问题，

，设置转码一样不行
原来的编码要转换一下，最新的分支理论都可以，我vs2017是没问题，有问题就找个软件把所有编码转换为带bom的，没有软件就随便敲个空格用qt creator保存
