### ISSUE TITLE
边框有根黑色的线

### ISSUE THREAD

**Issue by bairutai** [czyt1988/SARibbon#21]
window 左上部和上部有一根黑线是什么问题，改了半天去不掉
![微信图片_20210514173751](https://user-images.githubusercontent.com/10230669/118252333-38e06680-b4db-11eb-81d8-b090c58b0251.png)

**Comment by fietiger** [comment]
这个黑线存在三个边，最右边是没有的，最下面也有。目前还不清楚是什么原因

**Comment by czyt1988** [comment]
@bairutai @fietiger 你们看看最新版的是否还有所说的情况？
