### ISSUE TITLE
设置主窗口的窗口图标，有两种做法，结果不一样

### ISSUE THREAD

**Issue by MrLiuSheng** [czyt1988/SARibbon#22]
第一种，直接使用：
`setWindowIcon(QIcon(":/icon/icon/MainIcon.png"));`
结果显示：
窗口左上角显示有图标，但是有两个一模一样的，还是一大一小
![image](https://user-images.githubusercontent.com/73326699/125182380-316ddd00-e240-11eb-98b6-99102034212c.png)

新弹出的子窗口同样有继承
![image](https://user-images.githubusercontent.com/73326699/125182449-af31e880-e240-11eb-8667-e5fde00f9e57.png)

任务栏也有相应图标
![image](https://user-images.githubusercontent.com/73326699/125182402-52cec900-e240-11eb-9287-739b28f9a4fd.png)

第二种，使用SARibbonBar的对象设置图标
`     SARibbonBar *ribbon = ribbonBar();//制造一个类似的QMenuBar
    ribbon->setRibbonStyle(SARibbonBar::RibbonStyle::OfficeStyle);//设置标题样式
    ribbon->setWindowIcon(QIcon(":/icon/icon/MainIcon.png"));`
结果显示：
左上角只有一个主窗口图标
![image](https://user-images.githubusercontent.com/73326699/125182476-ddafc380-e240-11eb-994f-fadc95b4aa9d.png)

但是任务栏没有相应图标
![image](https://user-images.githubusercontent.com/73326699/125182491-f9b36500-e240-11eb-8440-a10091276baa.png)

新的子窗口也同样没有
![image](https://user-images.githubusercontent.com/73326699/125182499-0b950800-e241-11eb-9c8e-824c96e57467.png)

求教，请问怎么解决

**Comment by MrLiuSheng** [comment]
主窗口、任务栏及子窗口的图标设置

**Comment by czyt1988** [comment]
问题收到，我看看发自我的华为手机-------- 原始邮件 --------发件人： MrLiuSheng ***@***.***>日期： 2021年7月11日周日 中午12:11收件人： czyt1988/SARibbon ***@***.***>抄送： Subscribed ***@***.***>主    题： [czyt1988/SARibbon] 设置主窗口的窗口图标，有两种做法，结果不一样 (#22)

一种，直接使用：

setWindowIcon(QIcon(":/icon/icon/MainIcon.png"));

结果显示：

窗口左上角显示有图标，但是有两个一模一样的，还是一大一小



新弹出的子窗口同样有继承



任务栏也有相应图标



第二种，使用SARibbonBar的对象设置图标

    ribbon->setRibbonStyle(SARibbonBar::RibbonStyle::OfficeStyle);//设置标题样式 ribbon->setWindowIcon(QIcon(":/icon/icon/MainIcon.png"));

结果显示：

左上角只有一个主窗口图标



但是任务栏没有相应图标



新的子窗口也同样没有



求教，请问怎么解决

**Comment by czyt1988** [comment]
c50b5已经改好，mainwindow的connerwidget其中的topleft就是处理图标的，我这边又绘制了一个导致重复绘制了，直接用第一种方法即可

**Comment by MrLiuSheng** [comment]
问题已解决，谢谢
