### ISSUE TITLE
双击tab时会触发category显示或隐藏 ，当触发隐藏时，不会立即隐藏，需要鼠标焦点在其他地方触发，此区域才会隐藏

### ISSUE THREAD

**Issue by LiuSheng66** [czyt1988/SARibbon#26]
双击tabBar时：
触发效果：当是显示时，双击，category可以立即从隐藏变成显示状态
触发效果：当是隐藏时，双击，category**不可以**立即从显示变成隐藏状态
以下是是示例图：
![20210819_165554](https://user-images.githubusercontent.com/73326699/130040231-221386e7-0245-4420-83d1-82d3ebffd757.gif)

**Comment by czyt1988** [comment]
目前看office是会收回去，后续考虑加入类似office的动画效果

**Comment by czyt1988** [comment]
暂时设计如此，不更改
