### ISSUE TITLE
在ubuntu 16.04下 面板不显示

### ISSUE THREAD

**Issue by jinlong631** [czyt1988/SARibbon#28]
在ubuntu 下编译运行后 rabbon的菜单不显示

**Comment by czyt1988** [comment]
能否截个图，我这边还没有ubuntu系统

**Comment by jinlong631** [comment]
怎么可以发图片？粘贴不过来呢 @czyt1988

**Comment by jinlong631** [comment]
发你邮箱吧

**Comment by czyt1988** [comment]
ubuntu上的显示问题后面专门进行修复，可能是Ubuntu的菜单栏机制问题，涉及的改动可能比较大，SARibbonBar是继承menubar的，按目前看，可能要直接绘制一个widget在上面，这只是猜测，目前我在配置虚拟机，后续会专门针对Ubuntu进行优化

**Comment by czyt1988** [comment]
麻烦试试dev[ab9659c](https://github.com/czyt1988/SARibbon/commit/ab9659c5b86ec0bc8f7819400201b131cb6781ec)分支的这个改动，添加了一个第三方的frameless库，把setNativeMenuBar设置为false

**Comment by czyt1988** [comment]
时间过久，次问题关闭
