### ISSUE TITLE
ribbon中某些控件的高度不太匹配

### ISSUE THREAD

**Issue by chenzt2020** [czyt1988/SARibbon#32]
![image](https://user-images.githubusercontent.com/59409442/153745804-e7cd7e96-2e01-4430-810e-af82f262ced5.png)

屏幕尺寸：1920x1080
Qt版本：5.15.2

**Comment by czyt1988** [comment]
[fd3c61a](https://github.com/czyt1988/SARibbon/commit/fd3c61ad3adf83d82991f5904f33c806954f671f) 已修改

**Comment by czyt1988** [comment]
可以试试看效果
