### ISSUE TITLE
直接用源码编译错误

### ISSUE THREAD

**Issue by neomissing** [czyt1988/SARibbon#37]
![1647951658(1)](https://user-images.githubusercontent.com/22003930/159480761-2ed9b0a3-92c0-4f20-adb7-79d1cb88f096.png)

**Comment by czyt1988** [comment]
你是不编译成库直接把头文件和cpp文件引入工程吗？

需要预定义宏`SA_RIBBON_BAR_NO_EXPORT`：

参见SARibbonGlobal.h文件的33行

```c
#ifndef SA_RIBBON_BAR_NO_EXPORT
#if defined(SA_RIBBON_BAR_MAKE_LIB)  // 定义此宏将构建library
#define SA_RIBBON_EXPORT Q_DECL_EXPORT
#else
#define SA_RIBBON_EXPORT 
#endif
#endif
```
