### ISSUE TITLE
当windows桌面采用了缩放后，图标和字体比例错误

### ISSUE THREAD

**Issue by Nonce-lv** [czyt1988/SARibbon#41]
如题。
windows11，3K屏，缩放200%，比例错误，完全不能显示。
但使用quick技术的没问题，用widget和qss的都出现比例错误。

**Comment by czyt1988** [comment]
由于我这边没有高清屏，没做相关测试，等我我更新一个dev版本，加上一些打印信息看看高清屏的情况，此类问题之前有个issue提到，我这边这周抽空解决一下

**Comment by czyt1988** [comment]
主要是qss的问题，qss定义了像素px，高清屏会显示异常，我调整了一下qss，使用了pt和em单位，你拉取一下最新的master[d8e8c01]分支试试

**Comment by czyt1988** [comment]
另外在main函数中添加如下代码：
```cpp
    QApplication app(argc, argv);
#if (QT_VERSION >= QT_VERSION_CHECK(5, 6, 0))
    QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif
```
