### ISSUE TITLE
LargeWidget下如何设置单行和双行文字

### ISSUE THREAD

**Issue by AndyYangjd** [czyt1988/SARibbon#43]
Hi，这个项目很棒，非常感谢。

想请教如题所示的问题：

1. 例子中的两行文字
![更改前](https://user-images.githubusercontent.com/44262434/165507096-6cd96c9a-c50e-4a23-bf42-66072c12c5a0.png)
2. 修改之后的单行文字
![更改后](https://user-images.githubusercontent.com/44262434/165507000-73bf05bf-f6da-4caa-bd77-14ae803376e1.png)

请问如果设置单行或双行显示？谢谢

**Comment by czyt1988** [comment]
在`SARibbonBar::RibbonStyle`中有4种模式，其中以TwoRow结尾的是可以指定文本是否换行，非TwoRow结尾都是会换行，决定是否换行通过静态函数：`SARibbonToolButton::setLiteStyleEnableWordWrap`来设置，这个函数需要在构建ui之前调用，否则需要全部刷新才看到效果。在例子中有相关例子，由于我在用手机没法给你截图。
例子里面有个word wrap in 2row的按钮，切换后需要切换一下ribbon的style,强制重新计算尺寸才能看到效果

**Comment by AndyYangjd** [comment]
我这边选用的是wps风格（非两行），我这边发现三行模式下是否换行好像是跟文字的长度有关。当文字长度足够长的时候才会换行。是否有一些机制（检验到字符串中间有空格），可以强制三行模式下换行？

测试如下图所示：
![图片](https://user-images.githubusercontent.com/44262434/165661140-d140f14e-8014-4395-a7dd-53e71c4d3831.png)

我是将mainwindow.cpp中的部分代码修改如下：
```
# 修改save按扭的字符串
 QAction* actSave = createAction(tr("New Terminal"), ":/icon/icon/save.svg");

# 修改 show context 的字符串
QAction* actShowContext = createAction(tr("new Script"), ":/icon/icon/showContext.svg");

# 修改 delete context 的字符串
QAction* actDeleteContext = createAction(tr("create Script"), ":/icon/icon/deleteContext.svg");
```

Plus: 刚发现了一种解决方案，代码如下图：
···
QAction* act_new_script= createAction(tr("new               Script"), ":/image/image/save.png");
···

结果如下图：
![图片](https://user-images.githubusercontent.com/44262434/165661986-6f8577e6-a232-469d-95f0-7a7ad7471ee9.png)

**Comment by AndyYangjd** [comment]
一个新的问题是我这边用Qt6.2无法编译成功，只能用Qt5.15编写

**Comment by czyt1988** [comment]
> 

qt6没试过，你可以提到新的issues里，我专门处理一下

**Comment by czyt1988** [comment]
> 我这边选用的是wps风格（非两行），我这边发现三行模式下是否换行好像是跟文字的长度有关。当文字长度足够长的时候才会换行。是否有一些机制（检验到字符串中间有空格），可以强制三行模式下换行？
> 
> 测试如下图所示： ![图片](https://user-images.githubusercontent.com/44262434/165661140-d140f14e-8014-4395-a7dd-53e71c4d3831.png)
> 
> 我是将mainwindow.cpp中的部分代码修改如下：
> 
> ```
> # 修改save按扭的字符串
>  QAction* actSave = createAction(tr("New Terminal"), ":/icon/icon/save.svg");
> 
> # 修改 show context 的字符串
> QAction* actShowContext = createAction(tr("new Script"), ":/icon/icon/showContext.svg");
> 
> # 修改 delete context 的字符串
> QAction* actDeleteContext = createAction(tr("create Script"), ":/icon/icon/deleteContext.svg");
> ```
> 
> Plus: 刚发现了一种解决方案，代码如下图：
> 
> ```
> # 在new和script中间空格多一些
> QAction* act_new_script= createAction(tr("new               Script"), ":/image/image/save.png");
> ```
> 
> 结果如下图： ![图片](https://user-images.githubusercontent.com/44262434/165661986-6f8577e6-a232-469d-95f0-7a7ad7471ee9.png)

换行的确和文字长度有关，在src/SARibbonBar/SARibbonToolButton.cpp中，会对文字长度进行评估，可见：`void SARibbonToolButton::reCalcSizeHint(QSize s)`的这一段：
```cpp
//! 1 先获取最优的文字textRange
                {
                    const int maxTrycount = 3;
                    int trycount          = 0;
                    int alignment         = Qt::TextShowMnemonic | Qt::TextWordWrap;
                    do {
                        //先计算两行文本的紧凑矩形
                        //从一半开始逐渐递增
                        textRange.setWidth(s.width() / 2 + (s.width() / 2) * (float(trycount) / maxTrycount));
                        textRange = fm.boundingRect(textRange, alignment, text());
                        if (textRange.height() <= (fm.lineSpacing() * 2)) {
                            //保证在两行
                            m_isWordWrap = (textRange.height() > fm.lineSpacing());
                            break;
                        }
                        ++trycount;
                    } while (trycount < 3);
                }
```
我会尝试3次，以保证得到一个较为紧凑的文本

**Comment by AndyYangjd** [comment]
好的，感谢
