### ISSUE TITLE
Qt6.2无法编译通过

### ISSUE THREAD

**Issue by AndyYangjd** [czyt1988/SARibbon#44]
本工程在Qt5.15版本可以正常通过，但是无法在win10上面Qt6.2版本中的QtCreator编译通过，编译输入如下图所示：
![图片](https://user-images.githubusercontent.com/44262434/165694534-16f9949b-1ce1-443d-9691-6353e74b8d9c.png)

是否可以在Release中增加编译过的lib库文件，提供给用户使用？谢谢

**Comment by czyt1988** [comment]
从错误信息看是Qt的jom error 2错误，和程序代码无关，确认一下是否jom.exe的路径有问题

**Comment by czyt1988** [comment]
我qt6.4 MinGW64-bit是可以编译成功的，从你反馈的错误信息看是编译器配置问题

**Comment by AndyYangjd** [comment]
是否可以在项目的Relase中放入一些编译后SARibbon库文件，文件内容如下图所示：
![图片](https://user-images.githubusercontent.com/44262434/167280648-27b8df0e-2de8-4126-9c0b-02b116ef4df5.png)


![图片](https://user-images.githubusercontent.com/44262434/167280500-59ada667-3547-4d0d-88ca-cc82935b89a0.png)
用这个库的应该编程水平都还Ok，大部分用户只需要知道头文件+库路径就可以，cmake写起来也简单：
```cmake
include_directory(include)
link_directories(lib)
add_executable(${PROJECT_NAME} xxx.cpp)
target_link_libraries(${PROJECT_NAME} SARibbonBar XXX)

file(GLOB LIBS_PATH lib/*)
file(COPY ${LIBS_PATH} DESTINATION ${CMAKE_CURRENT_SOURCE_DIR}/XXX)
```

**Comment by czyt1988** [comment]
因为陆续还有一些改动和不完善的地方，暂时还未到release版本，等我感觉适合发布了，我会发布一个版本的

**Comment by AndyYangjd** [comment]
> 因为陆续还有一些改动和不完善的地方，暂时还未到release版本，等我感觉适合发布了，我会发布一个版本的

ok，那我把这个issue关闭了，应该是我这边环境配置的原因。
