### ISSUE TITLE
Gallery尺寸缩放

### ISSUE THREAD

**Issue by AndyYangjd** [czyt1988/SARibbon#45]
Hi，如下图所示：
![图片](https://user-images.githubusercontent.com/44262434/166107993-d78014c3-4e16-42c8-bd9c-71be72dfc266.png)

当有Gallery时，整行会被填充，看起来像是若干个Gallery共同均分这个行空间。但是我这里每个Gallery里的图标数量不同，如上图所示，看起来不是特别好看。
请问下：怎么才能让每个Gallery的宽度按照里面图标的数量自动缩放宽度？谢谢

**Comment by czyt1988** [comment]
可以调用`SARibbonPannel::setExpanding`取消掉扩展，SARibbonPannel::addGallery在addGallery函数内部给SARibbonPannel设置了扩展

```cpp
/**
 * @brief SARibbonPannel::addGallery
 * @return
 * @note SARibbonPannel将拥有SARibbonGallery的管理权
 */
SARibbonGallery* SARibbonPannel::addGallery()
{
    SARibbonGallery* gallery = RibbonSubElementDelegate->createRibbonGallery(this);

    addWidget(gallery, SARibbonPannelItem::Large);

    setExpanding();
    return (gallery);
}
```

这个似乎有点多余，可以去掉

**Comment by czyt1988** [comment]
你可以在调用`SARibbonPannel::addGallery`,再调用setExpanding(false)取消掉拉伸
如:
```cpp
SARibbonPannle* pannel = new SARibbonPannle();
...
SARibbonGallery* gallery = pannel->addGallery();
...
pannel->setExpanding(false);
```

**Comment by AndyYangjd** [comment]
pannel->setExpanding(false) 设置之后，每个包含gallery的panel尺寸是固定的，当图标多的时候拥挤在一起，如下图所示。
![图片](https://user-images.githubusercontent.com/44262434/166129760-eae01846-2b89-47c0-8aa3-8fd63f0b187c.png)
是否可以像如下图这样，设计一个Hbox，可以设置内部panel的相互之间的缩放比例？或者有一个设置每个包含gallery的pannel的水平尺寸？
![图片](https://user-images.githubusercontent.com/44262434/166129824-04a42435-db5d-4096-aa30-d946da42c84a.png)

**Comment by czyt1988** [comment]
> pannel->setExpanding(false) 设置之后，每个包含gallery的panel尺寸是固定的，当图标多的时候拥挤在一起，如下图所示。 ![图片](https://user-images.githubusercontent.com/44262434/166129760-eae01846-2b89-47c0-8aa3-8fd63f0b187c.png) 是否可以像如下图这样，设计一个Hbox，可以设置内部panel的相互之间的缩放比例？或者有一个设置每个包含gallery的pannel的水平尺寸？ ![图片](https://user-images.githubusercontent.com/44262434/166129824-04a42435-db5d-4096-aa30-d946da42c84a.png)

可以在expanding的pannel加入一个factor来调整缩放比例，其实可以设置Gallery的最小尺寸来控制，你可以先这样试试

**Comment by czyt1988** [comment]
> > > pannel->setExpanding(false) 设置之后，每个包含gallery的panel尺寸是固定的，当图标多的时候拥挤在一起，如下图所示。 ![图片](https://user-images.githubusercontent.com/44262434/166129760-eae01846-2b89-47c0-8aa3-8fd63f0b187c.png) 是否可以像如下图这样，设计一个Hbox，可以设置内部panel的相互之间的缩放比例？或者有一个设置每个包含gallery的pannel的水平尺寸？ ![图片](https://user-images.githubusercontent.com/44262434/166129824-04a42435-db5d-4096-aa30-d946da42c84a.png)
> > 
> > 
> > 可以在expanding的pannel加入一个factor来调整缩放比例，其实可以设置Gallery的最小尺寸来控制，你可以先这样试试
> 
> 设置Gallery的最小尺寸可以起到效果。 但是设置expanding的panel的factor调整缩放比例找不到相应的指令？要否将函数给出？
> 
> 另外Gallery中每个图标下方的名字过长是否可以变成两行显示，如matlab中下图所示： ![图片](https://user-images.githubusercontent.com/44262434/166413893-621883bb-3a5d-45bd-a74b-4b1a18acb659.png)

1、缩放因子这个功能目前没有，后续考虑添加
2、长文本换行这个可以通过SARibbonGalleryGroup来设置，在调用SARibbonGallery::addCategoryActions时，会返回一个SARibbonGalleryGroup，这个其实是一个QListView，QListView可以设置换行属性QListview::setWrapping

**Comment by AndyYangjd** [comment]
> > > > pannel->setExpanding(false) 设置之后，每个包含gallery的panel尺寸是固定的，当图标多的时候拥挤在一起，如下图所示。 ![图片](https://user-images.githubusercontent.com/44262434/166129760-eae01846-2b89-47c0-8aa3-8fd63f0b187c.png) 是否可以像如下图这样，设计一个Hbox，可以设置内部panel的相互之间的缩放比例？或者有一个设置每个包含gallery的pannel的水平尺寸？ ![图片](https://user-images.githubusercontent.com/44262434/166129824-04a42435-db5d-4096-aa30-d946da42c84a.png)
> > > 
> > > 
> > > 可以在expanding的pannel加入一个factor来调整缩放比例，其实可以设置Gallery的最小尺寸来控制，你可以先这样试试
> > 
> > 
> > 设置Gallery的最小尺寸可以起到效果。 但是设置expanding的panel的factor调整缩放比例找不到相应的指令？要否将函数给出？
> > 另外Gallery中每个图标下方的名字过长是否可以变成两行显示，如matlab中下图所示： ![图片](https://user-images.githubusercontent.com/44262434/166413893-621883bb-3a5d-45bd-a74b-4b1a18acb659.png)
> 
> 1、缩放因子这个功能目前没有，后续考虑添加 2、长文本换行这个可以通过SARibbonGalleryGroup来设置，在调用SARibbonGallery::addCategoryActions时，会返回一个SARibbonGalleryGroup，这个其实是一个QListView，QListView可以设置换行属性QListview::setWrapping

1. `QListview::setWrappin(true)` 之后效果基本上没有变化。尝试了增加两个字母之间的空格也基本上没有效果。
2. 虽然本工程证书是MIT，但是如果未来基于本控件的商业产品盈利的话，如何反馈本工程？我看到有一个商业控件：QtitanRibbon 跟本工程很相似，是否是本工程的商业化产品？如果未来反馈本工程的话，是购买QtianRibbon的证书吗？

**Comment by czyt1988** [comment]
`QListview::setWrappin(true) 之后效果基本上没有变化。尝试了增加两个字母之间的空格也基本上没有效果`

这个我下来看看是如何设置

**Comment by czyt1988** [comment]
> 虽然本工程证书是MIT，但是如果未来基于本控件的商业产品盈利的话，如何反馈本工程？我看到有一个商业控件：QtitanRibbon 跟本工程很相似，是否是本工程的商业化产品？如果未来反馈本工程的话，是购买QtianRibbon的证书吗？

`QtianRibbon`和本项目无关，这是一个商业控件，我当时想用ribbon发现只有商业的`QtianRibbon`才开发了这个项目，如果未来基于本控件的商业产品盈利的话，在MIT协议是无要求的，只需附有MIT授权协议和版权声明，`SARibbon`当前虽然能正常使用，但我希望能有更多人使用并反馈问题使其完善，也希望有别人能赋予它更高的价值

**Comment by AndyYangjd** [comment]
> `QtianRibbon`和本项目无关，这是一个商业控件，我当时想用ribbon发现只有商业的`QtianRibbon`才开发了这个项目，如果未来基于本控件的商业产品盈利的话，在MIT协议是无要求的，只需附有MIT授权协议和版权声明，`SARibbon`当前虽然能正常使用，但我希望能有更多人使用并反馈问题使其完善，也希望有别人能赋予它更高的价值

感谢，期待未来有机会可以一起合作

**Comment by czyt1988** [comment]
> `QListview::setWrappin(true) 之后效果基本上没有变化。尝试了增加两个字母之间的空格也基本上没有效果`
> 
> 这个我下来看看是如何设置

这个我说错了，文字换行的api是`QListview::setWordWrap(bool on)`，你试试这个

**Comment by AndyYangjd** [comment]
> 这个我说错了，文字换行的api是`QListview::setWordWrap(bool on)`，你试试这个

还是不行，单纯设置 `QListview::setWordWrap(bool on)` 或`QListview::setWrappin(true)`或两者都设置均无效。这个问题看起来有些棘手。

**Comment by czyt1988** [comment]
> > 这个我说错了，文字换行的api是`QListview::setWordWrap(bool on)`，你试试这个
> 
> 还是不行，单纯设置 `QListview::setWordWrap(bool on)` 或`QListview::setWrappin(true)`或两者都设置均无效。这个问题看起来有些棘手。

这个我上班看看，现在手头没环境无法测试

**Comment by AndyYangjd** [comment]
> 这个我上班看看，现在手头没环境无法测试
好的，感谢。

**Comment by czyt1988** [comment]
我看了一下QListView的确无法直接让文本换行，但要实现此功能的话也不是太复杂，只需要修改SARibbonGalleryGroupItemDelegate（位于SARibbonGalleryGroup.cpp/h）的paintIconWithText函数即可，但是我看了一下wps和office的ribbon风格，貌似没有这样设置的，matlab算比较特别的魔改了一下，我后面会对group加上此功能。
能否再提两个issues，一个是添加因子，一个是gallery文字换行，我标记为需求，避免我后续忘记了

**Comment by AndyYangjd** [comment]
> 能否再提两个issues，一个是添加因子，一个是gallery文字换行，我标记为需求，避免我后续忘记了

ok，那我把本问题关闭，再开两个新的issue
