### ISSUE TITLE
Gallery中每个图标下方的文字存在空格时，设置双行显示

### ISSUE THREAD

**Issue by AndyYangjd** [czyt1988/SARibbon#48]
实现如下图所示matlab中的效果：
![图片](https://user-images.githubusercontent.com/44262434/166932179-8bd58669-31bb-44ce-95f7-8640c3958f4c.png)

**Comment by AndyYangjd** [comment]
> 但感觉不是很好看，主要是宽度问题，你看看有什么建议？

一般下方的文字主要还是分为以下三种：

1. 单个单词（如 Signal）：这种有时候会单词比较长，图像的宽度不够，文字显示不全。
2. 两个单词（如Encode File）：这种情况下一般设置为两行比较好看。如果设置为单行，文字必须超出图片的宽度而导致无法显示全。
3. 三个单词（如Digital Signal Process）：这种情况下也还是两行比较好看些，像matlab那样，最后的字母可以显示不全。

综上：从matlab的视觉效果看，它的各个图标块是固定宽度的，而且这个固定的宽度值一般是超出单个长字母的宽度的。整体布局如下图所示，其中text是双行高度：
![图片](https://user-images.githubusercontent.com/44262434/167084470-35e892ab-51e2-4529-a6de-4070f079d6f8.png)

**Comment by czyt1988** [comment]
你试试这个是否是你想要的效果：e4ca261
![image](https://user-images.githubusercontent.com/7260393/167134577-e6680caf-de77-46e9-b8c1-0be2715bd08e.png)

另外我调整了一些函数名称，可能会遇到一些错误

大致用法：
```cpp
    SARibbonGalleryGroup* group1 = gallery->addCategoryActions(tr("Files"), galleryActions);
    group1->setGalleryGroupStyle(SARibbonGalleryGroup::IconWithWordWrapText);
```

可以实现不同的展示效果：

![image](https://user-images.githubusercontent.com/7260393/167134782-5f093e3c-5c7d-4ec5-8173-991b368de17b.png)

**Comment by AndyYangjd** [comment]
> group1->setGalleryGroupStyle(SARibbonGalleryGroup::IconWithWordWrapText);

1. 我在代码中增加了这一行报错，提示：setGalleryGroupStyle 不是 SARibbonGalleryGroup的函数。这里应该是你新加入的函数吧。
2. 相邻图标看起来文字长的时候会有些拥挤，是否可以设置间距为文本的长度？
3. 另外我觉得当存在多个Group的时候，多个Group中间的间距太大视觉效果不好，所以，我把每个Group生成一个Gallery，而不是放在一起。

2和3描述的问题 如下图所示：
![图片](https://user-images.githubusercontent.com/44262434/167150461-c5703335-55d9-4a48-84ef-1bcd167ae73b.png)

**Comment by czyt1988** [comment]
不能显示完全问题，我添加了接口，可以设置最小宽度

![image](https://user-images.githubusercontent.com/7260393/167279412-7ab4fc44-1f15-4350-b0c1-4dfbf7b81b08.png)

我提交到了dev分支c478bb8，你可以：
```
git pull origin dev:dev
checkout dev
```
拉取dev分支试试

```cpp
    SARibbonGalleryGroup* group1 = gallery->addCategoryActions(tr("Files"), galleryActions);
    group1->setGalleryGroupStyle(SARibbonGalleryGroup::IconWithWordWrapText);
    group1->setGridMinimumWidth(80);
    galleryActions.clear();
    galleryActions.append(lambdaCreateGalleryAction("Photoshop", ":/gallery-icon/icon/gallery/Photoshop.svg"));
    ......
    SARibbonGalleryGroup* group2 = gallery->addCategoryActions(tr("Apps"), galleryActions);
    group2->setGridMinimumWidth(80);
    gallery->setCurrentViewGroup(group1);
```

通过setGridMinimumWidth可以设置最小的grid宽度，这样所有都统一大小

**Comment by AndyYangjd** [comment]
>     SARibbonGalleryGroup* group2 = gallery->addCategoryActions(tr("Apps"), galleryActions);
>     group2->setGridMinimumWidth(80);
>     gallery->setCurrentViewGroup(group1);

非常感谢，这两条指令很完善。

> 另外我觉得当存在多个Group的时候，多个Group中间的间距太大视觉效果不好，所以，我把每个Group生成一个Gallery，而不是放在一起。

这个问题是否可以优化？matlab的布局如下图所示：
![图片](https://user-images.githubusercontent.com/44262434/167280419-d657c733-b0d6-401b-8baf-52ef7e4bed37.png)
![图片](https://user-images.githubusercontent.com/44262434/167280446-efd544f7-1199-4472-8adb-fd6f38cec30f.png)

**Comment by czyt1988** [comment]
> 这个问题是否可以优化？matlab的布局如下图所示：
这个准备优化，最近略忙，没来的及搞

**Comment by AndyYangjd** [comment]
非常感谢，这个增强功能不着急
