### ISSUE TITLE
Support Qt5 while building with cmake

### ISSUE THREAD

**Issue by thegoodtgg** [czyt1988/SARibbon#54]
in CMakeLists.txt
`
find_package(Qt6 COMPONENTS Core Widgets GUI)
if (NOT Qt6_FOUND)
    find_package(Qt5 5.15 REQUIRED COMPONENTS Core Widgets GUI)
    set(Qt_VERSION_MAJOR 5)
else()
    set(Qt_VERSION_MAJOR 5)
endif()
`

in src/SARibbonBar/CMakeLists.txt
`
target_link_libraries(${LIB_NAME} Qt${QT_VERSION_MAJOR}::Widgets)
`

**Comment by FelixBer** [comment]
Any idea why CMakeLists.txt is consistently spelled CMakelists.txt in the repo?

**Comment by czyt1988** [comment]
have been added  CMakeLists.txt in project,you can compile using cmake
