### ISSUE TITLE
求助，右上角的三个windowsbutton不显示

### ISSUE THREAD

**Issue by nebulall** [czyt1988/SARibbon#65]
我用的cmake，其他显示一切正常，就是右上角三个windowsbutton不显示，我用例子的.pro引入的方法是没问题的，可以显示出来，但用cmake集成就不显示。求助一下可能的原因。

**Comment by czyt1988** [comment]
不是使用designer做的吧？

**Comment by wanzhongping** [comment]
碰到同样的问题，用的designer @czyt1988

**Comment by nebulall** [comment]
This phenomenon is caused by incorrect SARibbon/source file path

 

 

 

发件人: ***@***.*** ***@***.***> 代表 wanzhongping
发送时间: 2023年5月25日 11:38
收件人: czyt1988/SARibbon ***@***.***>
抄送: nebulall ***@***.***>; Author ***@***.***>
主题: Re: [czyt1988/SARibbon] 求助，右上角的三个windowsbutton不显示 (Issue #65)

 

碰到同样的问题，用的designer @czyt1988 <https://github.com/czyt1988>
