### ISSUE TITLE
QAction在更改字体之后，会导致图表大小变化

### ISSUE THREAD

**Issue by NoWhere-NowHere-TLD** [czyt1988/SARibbon#69]
因为我想模仿word样式，所以将ribbon的相关字体更改为“微软雅黑”，但是更改样式之后，会导致图标大小改变，如下图所示

**Comment by NoWhere-NowHere-TLD** [comment]
由于之前设置的pannel高度不变，所以导致QAction的留白部分较多，有点不美观

**Comment by czyt1988** [comment]
我现在是根据字体来调整icon的高度的，微软雅黑的字体高度变大了，所以icon区域就变小了，这样也是为了适应不同字体的情况，你是用两行模式吧

**Comment by NoWhere-NowHere-TLD** [comment]
> 我现在是根据字体来调整icon的高度的，微软雅黑的字体高度变大了，所以icon区域就变小了，这样也是为了适应不同字体的情况，你是用两行模式吧

我用的默认的没动过，是三行模式，多谢大佬回复

**Comment by NoWhere-NowHere-TLD** [comment]
对了，大佬，一直想问，你写的“SARibbonStyleOption”中“配置文件定义ribbon的尺寸布局”这个功能，想使用的配置文件跟功能栏那个一样是xml吗

**Comment by czyt1988** [comment]
现在还不支持配置文件的定义StyleOption，有空加上，另外你能截取多几个对比图给我看看吗，你的显示器是什么分辨率，我看看不同设备上的显示效果

**Comment by NoWhere-NowHere-TLD** [comment]
> 现在还不支持配置文件的定义StyleOption，有空加上，另外你能截取多几个对比图给我看看吗，你的显示器是什么分辨率，我看看不同设备上的显示效果

我显示器是1080P的
![image](https://github.com/czyt1988/SARibbon/assets/53173671/cd4e0d30-9aa8-4590-9e55-f7a7a0f1586d)
这是我更改字体后的显示，图标太小，结果大图标虽然占了三行，但是显示出来只占两行，下部分有一行的留白。另外我更改了一下disable的字体显示，以前的字体在disable下不会变灰，主要是不太会用github，之前只在github上下载代码，大佬需要的话我可以把更改提交一下啥的

**Comment by NoWhere-NowHere-TLD** [comment]
> 正常不应该，看着像设置了2行模式，能否贴一下部分代码

是三行
![image](https://github.com/czyt1988/SARibbon/assets/53173671/01c90085-16e9-41ec-8aa3-90a66d6102d9)
不好意思，可能是我之前没说清楚，我是更改了字体之后导致图标变小，图标也是大图标，只是下面会空出一大片，就像下面这样
![image](https://github.com/czyt1988/SARibbon/assets/53173671/b4c83363-2b15-4f61-a2bb-b814a398c6e0)
我打算更改图标大小来实现，另外添加代码如下，在这行代码之外并没有更改相关样式设置，包括pannel和category
`//显示图表按钮
        m_showPlotAction=common::createAction(QString("图表显示"),":/icon/project/plot-display.svg");
        m_dataProcss_pannel->addLargeAction(m_showPlotAction);
        connect(m_showPlotAction,&QAction::triggered,this,&acousticPropagationLoss::setChannelNums);

        //数据框选按钮
        m_dataSelectionAction=common::createAction(QString("框选数据"),":/icon/icon/action3.svg");
        m_dataProcss_pannel->addSmallAction(m_dataSelectionAction);
        m_dataSelectionAction->setCheckable(true);

        //将框选的数据做傅里叶变换
        m_fftAction=common::createAction(QString("fft变换"),"");
        m_dataProcss_pannel->addSmallAction(m_fftAction);
        m_fftAction->setEnabled(false);
        connect(m_fftAction,&QAction::triggered,this,&acousticPropagationLoss::fftAction_trigger);

        QAction* testAction=common::createAction(QString("测试"),"");
        m_dataProcss_pannel->addSmallAction(testAction);
`
多谢大佬回复

**Comment by NoWhere-NowHere-TLD** [comment]
字体是在qss文件中改的，如下


SARibbonBar QWidget{
  font-family: "Microsoft YaHei";
}

**Comment by NoWhere-NowHere-TLD** [comment]
对了，我还更改了SARibbonStyleOption中的m_tabBarHeight

`
SARibbonStyleOption::SARibbonStyleOption()
{
    QFontMetrics fm = QApplication::fontMetrics();
    int lineSpacing = fm.lineSpacing();

    m_titleBarHeight                     = lineSpacing * 1.8;
//    m_tabBarHeight                       = lineSpacing * 1.5;
    m_tabBarHeight                       = lineSpacing * 2;
    m_ribbonbarHeightOfficeStyleThreeRow = m_titleBarHeight + m_tabBarHeight + (lineSpacing * 1.5) * 3
                                           + SARibbonPannel::pannelTitleHeight()
                                           + SARibbonPannelLayout::pannelContentsMargins().bottom()
                                           + SARibbonPannelLayout::pannelContentsMargins().top();
    recalc();
}`

我把1.5改成了2，然后在qss文件中，使用了如下参数：

`
SARibbonTabBar::tab {
  color: white;
  border: none;
  background: transparent;
  margin-top: 0em;
  margin-right: 0pt;
  margin-left: 0em;
  margin-bottom: 0em;
  min-width: 3em;
  max-width: 10em;
  min-height: 1.8em;
  max-height: 1.8em;
  padding-left: 1em;
  padding-right: 1em;
  padding-top: 0.1em;
  padding-bottom: 0.3em;
}
`

但我觉得这些跟Action的大小应该没关系把，我主要是为了复刻Word中tab栏中存在的padding，所以对上面的样式进行了更改

**Comment by czyt1988** [comment]
你拉取一下最新版本，我看你的css好像不是最新版本的

**Comment by czyt1988** [comment]
我知道了，这是正常显示，因为标准的office模式下，文本是两行高度，其布局如下：

![ribbon-toolbutton-largebutton](https://github.com/czyt1988/SARibbon/assets/7260393/31abb41e-486f-489e-b944-054ebdd70999)

示例的ribbon大小也是这样的
![image](https://github.com/czyt1988/SARibbon/assets/7260393/a22af14d-6ada-437f-a1b1-000d4d487451)

**Comment by NoWhere-NowHere-TLD** [comment]
照这个看的话，主要还是单行文字采用的icon策略是双行的，所以导致图标有点小，同时将字体换成微软雅黑后导致图标更小了，要不大佬，把全局字体换成微软雅黑，使用微软雅黑做适配吧，默认字体看着有点糊，怪怪的。

我看word还有个这种情况
![image](https://github.com/czyt1988/SARibbon/assets/53173671/32dd8b9f-9547-41e7-ba59-b8e479327428)
他这个图标和文字感觉是，如果高大于宽，并且字数不多的话，会竖着显示

其次感觉图标里面的下拉符号，文字一行的时候在文字下面，文字两行的时候排在文字右面，也就是不占高度
![image](https://github.com/czyt1988/SARibbon/assets/53173671/1ca1467c-8d4f-45c6-aba7-4a87bd62eff5)

**Comment by NoWhere-NowHere-TLD** [comment]
感觉大佬可以把图标高度的接口抛出来，不然有的图标是真的太小了（

**Comment by czyt1988** [comment]
你试试我昨天提交的dev分支[fa283ab](https://github.com/czyt1988/SARibbon/commit/fa283abff79949112290840ae6a66b28a9423aca)
我修改了换行显示的方法，调用`SARibbonToolButton::setEnableWordWrap`这个静态函数可以实现文字是否换行，文字换行就图标小，文字不换行就图标大

结合SARibbonBar的`SARibbonBar::setRibbonStyle`可以实现8种显示模式

具体效果：
office，3行模式不换行：
![image](https://github.com/czyt1988/SARibbon/assets/7260393/b01e7cac-acfb-43b2-bba4-def218ffe2fe)

office，3行模式换行：
![image](https://github.com/czyt1988/SARibbon/assets/7260393/d071482c-8299-4657-8e1d-5f7f3da7bf3a)

office，2行模式不换行：
![image](https://github.com/czyt1988/SARibbon/assets/7260393/e3ac917d-3b28-43e3-aa8e-72d68883d262)

office，2行模式换行：
![image](https://github.com/czyt1988/SARibbon/assets/7260393/1708f88c-fb85-48e3-8bec-6559d7038ea3)


wps，3行模式不换行：
![image](https://github.com/czyt1988/SARibbon/assets/7260393/9e82f23a-14c7-4387-96a3-061fb3c7531c)

wps，3行模式换行：
![image](https://github.com/czyt1988/SARibbon/assets/7260393/ded2c39f-fe14-4cee-b318-ee7e50445be2)

wps，2行 模式，不换行
![image](https://github.com/czyt1988/SARibbon/assets/7260393/d5860749-19ab-4379-954d-38a493da3ddc)

wps，2行模式，换行
![image](https://github.com/czyt1988/SARibbon/assets/7260393/f8f94987-63a9-49ff-800d-110f57a4d053)

**Comment by NoWhere-NowHere-TLD** [comment]
多谢大佬，我刚刚试了下，默认就是文字不换行嘛，图标大小感觉没啥变化:sob:，我在想是不是svg图标的原因，多谢大佬一直回复，多谢

**Comment by czyt1988** [comment]
![fcf43b019c15e6e38c7b8a837d16a47d_239876789-b4c83363-2b15-4f61-a2bb-b814a398c6e0](https://github.com/czyt1988/SARibbon/assets/7260393/51489c86-37cd-486c-a182-436f9168c9ef)
从你这个看就是文字换行了，你可以在ribbon构建之前调用`SARibbonToolButton::setEnableWordWrap(false);`这个静态函数，让不换行，不换行的文字会在下方显示，不会像你图片那样顶在上面的， 你可以参考我example里面word wrap这个按钮的实现方法动态设置是否换行：`MainWindow::onActionWordWrapTriggered`

**Comment by NoWhere-NowHere-TLD** [comment]
多谢大佬，破案了，我之前不知道什么时候把SARibbonBar.dll动态库放在了程序的release文件夹里面，导致调用动态库时一直使用的都是老版本的动态库，刚刚我使用setEnableWordWrap这个函数时报错，排查了一遍才发现这个问题:grin:

**Comment by NoWhere-NowHere-TLD** [comment]
不过又有一个问题，文字不居中显示了
![image](https://github.com/czyt1988/SARibbon/assets/53173671/05a6ceb0-d75e-4cdc-b941-b15274c8c355)

**Comment by NoWhere-NowHere-TLD** [comment]
对了大佬，你SARibbonToolButton::setEnableWordWrap函数的注释，调用这个之后再调用的是ribbonBar()->updateRibbonGeometry();吧，但是你注释还是RibbonSubElementStyleOpt.recalc()

**Comment by czyt1988** [comment]
更新一下master分支或dev分支的，我昨天提交了，改了对齐方式

**Comment by NoWhere-NowHere-TLD** [comment]
已经更新哩，但是没对齐，不知道为啥，我fork到我自己的库了，第一次好好使用git，还不太会

**Comment by WHU-ZhuLin** [comment]
同问，图标和文字不对齐，而且图标好小哇

**Comment by czyt1988** [comment]
> 已经更新哩，但是没对齐，不知道为啥，我fork到我自己的库了，第一次好好使用git，还不太会

> 同问，图标和文字不对齐，而且图标好小哇

@NoWhere-NowHere-TLD @WHU-ZhuLin 

2行模式之前设置了左对齐，的确不好看，拉取最新的吧，已经都调整为中间对齐了[98e472a](https://github.com/czyt1988/SARibbon/commit/98e472ad000a95a134f681897b5364587a48727c)

**Comment by WHU-ZhuLin** [comment]
收到

**Comment by NoWhere-NowHere-TLD** [comment]
多谢大佬，大佬辛苦了！不过我想说的是，我一直都是三行模式没变过（x

**Comment by czyt1988** [comment]
重新调整了一个布局，tag 0.5.0版本：

- 2行模式和3行模式都可以指定文本是否换行，如果想图标大，就选择文本不换行，直接调用SARibbonBar::setEnableWordWrap
- 文本换行的情况下，如果文本比较短，会有一行的留白，可以手动添加\n进行文本换行，添加\n的文本在不换行模式下不会进行换行显示

具体布局说明可参见：https://github.com/czyt1988/SARibbon/blob/master/doc/ribbon-toolbutton.md

**Comment by NoWhere-NowHere-TLD** [comment]
多谢大佬，这也太勤快了。
