### ISSUE TITLE
使用qt 5.14 + clion + cmake 编译可以，但是运行的时候找不到链接库lib

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#74]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/bcb04fb8-4cc1-4dd4-ba58-3debccb720ca)

**Comment by leonjang** [comment]
@czyt1988 @OgreTransporter @shelltdf @mingweiLIU 大佬，求助求助~ 有空帮忙看看呀

**Comment by czyt1988** [comment]
cmake有点问题
你把src/SARibbonBar/CMakeLists.txt的142行的

```cmake
target_compile_definitions(${SARIBBONBAR_LIB_NAME} PRIVATE SA_COLOR_WIDGETS_NO_DLL)
```

改为看看

```cmake
target_compile_definitions(${SARIBBONBAR_LIB_NAME} PRIVATE SA_COLOR_WIDGETS_MAKE_LIB)
```

**Comment by czyt1988** [comment]
试试v0.6.1

**Comment by leonjang** [comment]
@czyt1988 感谢楼主回复， 但是貌似还是不行， 环境设置如下：

**Comment by leonjang** [comment]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/1687d8a0-25b5-4446-a1fd-c18ed952311a)
![image](https://github.com/czyt1988/SARibbon/assets/33179543/a27433bf-42b3-4220-a055-a2c098cb21e4)

**Comment by leonjang** [comment]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/69eb39d4-a060-4319-aeaa-cd43ff6f3773)

**Comment by leonjang** [comment]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/3c4eeda5-8c9c-44e7-9b21-60f346eb8ed5)
run的时候-1073741511， debug的时候跳出2个框， 这是第二个
![Uploading image.png…]()

**Comment by czyt1988** [comment]
我没用过clion，这种情况就是编译器加载的dll和exe需要的dll不是一个版本导致的
你先确保用的是哪个版本的qt编译的，然后打开对于版本qt的cmd（位于不同bin目录下的qtenv.bat，例如5.14.2/msvc2017_64/bin/qtenv.bat或者5.14.2/mingw73_64/bin/qtenv.bat），cd到exe下的目录，然后执行windeployqt MainWindowExample.exe看看，单独点击exe运行看看

**Comment by leonjang** [comment]
@czyt1988  感谢，已经解决啦，确实是需要的dll版本不同的问题
