### ISSUE TITLE
好东西,可惜加入到我的工程一运行出来整个界面卡死

### ISSUE THREAD

**Issue by gooker** [czyt1988/SARibbon#75]
我的界面控件比较多,包括菜单/按钮/qtpropertybrowser/graphicsview/table等等
能给个分析方向吗.
例子运行没有问题.

**Comment by czyt1988** [comment]
我大工程都是上千个action，且你这些控件都是很常见的，并没有什么问题
你可以参考【dev分支】：https://github.com/czyt1988/data-workbench，这是一个类似visio的工作流软件，qtpropertybrowser/graphicsview/table/tree/python交叉调用都涉及
另外也可以参考：https://gitee.com/DISOGitee/FastCAE，这是一个CAE三维建模和仿真软件，vtk，occ这些三维建模的库都包含

**Comment by gooker** [comment]
<widget class="QMenuBar" name="menubar"> 有QMenuBar就会假死,去掉就正常了.
