### ISSUE TITLE
quickAccessBars中建立新的action， 鼠标移动到上面没有反应，只有在很边缘的地方，才有选中的效果

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#77]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/721edaa6-a706-458e-ba72-494cf4a570ad)

**Comment by leonjang** [comment]
加了3个action的情况下，最后一个action就可以正常显示选中状态，  红标代表鼠标的位置
![image](https://github.com/czyt1988/SARibbon/assets/33179543/a41a5d66-4711-4fa9-bfd0-9f7924c716f7)

**Comment by leonjang** [comment]
有个小技巧可以解决这个办法，但是有点怪怪的。
![image](https://github.com/czyt1988/SARibbon/assets/33179543/f2f77f94-25a8-490b-b81e-685520516b1c)

**Comment by leonjang** [comment]
先设置2个空的action，就可以解决这个问题

**Comment by leonjang** [comment]
但是换了新的分辨率后，
![image](https://github.com/czyt1988/SARibbon/assets/33179543/63213ff6-33af-45b4-ba01-1dd9728a4bed)
这样加2个action的方法就失效了，  第一个save的图标会点击不了

**Comment by czyt1988** [comment]
请问你的屏幕分辨率是多少

**Comment by leonjang** [comment]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/e2ab20ed-e7a3-45ea-839c-9b81eee1921f)
楼主好，分辨率如上

**Comment by leonjang** [comment]
2个屏幕都是

**Comment by leonjang** [comment]
@czyt1988 楼主，排查了很久，发现这个跟一个QVTKOpenGLNativeWidget的类有关，过程如下， 
![img_v2_82ec1eb1-3159-433f-bd76-256b5bbab73g](https://github.com/czyt1988/SARibbon/assets/33179543/ad1c7bb7-7fd1-49c3-badc-2cd95dfceff2)
红框中的这部分内容，直接放的时候，不能点击
必须加一个间隔，才能点击
像这样
![img_v2_34e69f40-0aa4-4345-bc2c-86ffbd45c8cg](https://github.com/czyt1988/SARibbon/assets/33179543/b91d7ed5-0978-410b-8b3a-a3ae3cdb7ca4)
注释掉所有mainwindow的代码进行排查，发现是这个类QVTKOpenGLNativeWidget导致的
只要QVTKOpenGLNativeWidget创建了， 就会有一个黑边
![img_v2_3e70d15d-badd-47c1-aec4-072778f0acbg](https://github.com/czyt1988/SARibbon/assets/33179543/91c56c22-f513-456f-b387-6885a059b1e4)
不对QVTKOpenGLNativeWidget进行创建，就正常
![img_v2_934bed95-8e58-47f3-a858-20d35efc1cdg](https://github.com/czyt1988/SARibbon/assets/33179543/3297ffea-fafd-4a5e-aaeb-a8550be7b4d6)
![image](https://github.com/czyt1988/SARibbon/assets/33179543/1b75a924-2574-41bf-8c69-472d6562c1f8)
求助楼主啊！十分感谢！~

**Comment by leonjang** [comment]
这个应该不是楼主的框架的问题，是VTK的问题， 我先把这个close掉了
