### ISSUE TITLE
ubuntu下点击标题栏，拖动窗口，无法往屏幕边缘拖动隐藏部分窗口

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#79]
楼主，寻求帮助啊，感谢

**Comment by leonjang** [comment]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/8fb57e3a-a773-41f3-bd64-8f366f864d87)

**Comment by leonjang** [comment]
windows下可以正常拖动出边界，  ubuntu下却不行

**Comment by czyt1988** [comment]
ubuntu下我暂时没进行更多测试
无法往屏幕边缘拖动隐藏部分窗口，所谓隐藏部分窗口是指什么呢？

**Comment by leonjang** [comment]
楼主好， 就是窗口的一半可以隐藏在任务栏一下，看不到了的意思

**Comment by czyt1988** [comment]
这个后续引入第三方的frameless框架来解决跨平台无边框问题，初步在[https://github.com/Bringer-of-Light/Qt-Nice-Frameless-Window](https://github.com/Bringer-of-Light/Qt-Nice-Frameless-Window)和[https://github.com/wangwenx190/framelesshelper](https://github.com/wangwenx190/framelesshelper)这两个之间选择

**Comment by leonjang** [comment]
我们之前用了CF Frameless+SARibbon框架去实现了一版，但是不适用于linux系统， 楼主采用这2个确实可以适用跨平台的问题，如果有需要，我也可以参与开发。

**Comment by leonjang** [comment]
采用[Qt-Nice-Frameless-Window](https://github.com/Bringer-of-Light/Qt-Nice-Frameless-Window)吧， 我来加入一起开发， 我之前加了一些代码，今天明天提交一些代码上去。

**Comment by leonjang** [comment]
不过[Qt-Nice-Frameless-Window](https://github.com/Bringer-of-Light/Qt-Nice-Frameless-Window) ，无法适用于linux系统

**Comment by czyt1988** [comment]
目前从源码看[https://github.com/wangwenx190/framelesshelper](https://github.com/wangwenx190/framelesshelper)是做过3端适应的，但使用前要进行一次初始化，不是很友好
