### ISSUE TITLE
请问如何设置最小化、最大化和关闭按钮WindowButtonGroup显示大小

### ISSUE THREAD

**Issue by HaojieTian** [czyt1988/SARibbon#8]
首先感谢分享代码。
![image](https://user-images.githubusercontent.com/49965646/90953653-19faf980-e4a0-11ea-847c-f41b2665b5d1.png)
windows button设置如下：
buttonMinimize->setFixedSize(40, 28);//原来设置：buttonMinimize->setFixedSize(30, 28);
buttonMaximize->setFixedSize(40, 28);//原来设置：buttonMaximize->setFixedSize(30, 28);
buttonClose->setFixedSize(40, 28);//原来设置：
WindowButtonGroup大小应该是120宽度，结果实际是100，改了好久没成功，不知道改哪里，能指明下吗？谢谢了！

**Comment by HaojieTian** [comment]
OK了，十分感谢！

**Comment by HorrZzz** [comment]
额，没看懂；我也是刚开始了解SARibbon，请问怎么才能修改 最小化 最大化 关闭按钮的大小呢？在高分屏上默认的按钮显示太小了....

**Comment by czyt1988** [comment]
> 额，没看懂；我也是刚开始了解SARibbon，请问怎么才能修改 最小化 最大化 关闭按钮的大小呢？在高分屏上默认的按钮显示太小了....

正常来讲，qt会自动处理高分屏的问题，目前最新版已经在4k屏，且是双屏幕上测试过没问题

要应对高分屏需要如下几个准备：

### 1、main函数的QApplication创建之前，设置一个静态属性`AA_EnableHighDpiScaling`

```cpp
int main(int argc, char* argv[])
{
#if (QT_VERSION >= QT_VERSION_CHECK(5, 6, 0))
    QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif
    QApplication a(argc, argv);
....
}
```

### 2、Qt版本保证在Qt5.14以上，Qt5.14修正了Qt自身高分屏的bug
