### ISSUE TITLE
字体大小问题， 设置pannel字体大小无效，icon下的字会显示一半

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#80]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/f57e6769-9d20-4484-b155-d4871f2e9ec1)
楼主好，如上，
1.  只对第一个pannel设置字体大小，字体并没有变大；
2. icon下的save as的字， 超过2行，下面的字就会显示一部分，一部分被吃掉了

分辨率参数如下：
![Uploading image.png…]()

**Comment by czyt1988** [comment]
请问是最新的dev分支吗

**Comment by leonjang** [comment]
是main分支，记起来了，好像改了标题栏，用了CFframless去替换SAribbonMainWindow的父类QMainWindow；请问楼主，
![image](https://github.com/czyt1988/SARibbon/assets/33179543/921f6695-67a3-408b-9123-a7d30930fc7f)
我使用了2row的Office2013风格， 字无法完全显示，可以通过调qss去扩大pannel的高度吗？这个理论上是可以的不？

**Comment by czyt1988** [comment]
ribbon的菜单是通过`SARibbonToolButton`来显示的，`SARibbonToolButton`的显示逻辑是先计算出文本高度，再计算icon尺寸，优先保障能显示出2行文本高度，至于为何会有一小点显示不全，应该是换行后行间距的问题，我计算两行的高度没有使用`QFontMetrics`实际计算有换行后的高度，而是用`QFontMetrics::lineSpacing`*2这样来计算的，具体可见SARibbonToolButton.cpp的`SARibbonToolButton::PrivateData::calcTextDrawRectHeight`函数

针对此问题，你可以这样快速修改一下：
SARibbonToolButton.cpp的19行附件，有个`SARIBBONTOOLBUTTON_WORDWRAP_TEXT_FACTOR`宏，目前设置为2.05
你可以把它设置为2.1或者更大试试

后续我会直接计算换行文本的高度来替换掉这种估算

**Comment by czyt1988** [comment]
你好，你可以帮我测试一下，帮忙把`SARibbonToolButton::PrivateData::calcTextDrawRectHeight`改为如下：

```cpp
int SARibbonToolButton::PrivateData::calcTextDrawRectHeight(const QStyleOptionToolButton& opt) const
{
    if (SARibbonToolButton::LargeButton == mButtonType) {
        if (isEnableWordWrap()) {
            return opt.fontMetrics.lineSpacing() * SARIBBONTOOLBUTTON_WORDWRAP_TEXT_FACTOR + opt.fontMetrics.leading();
        } else {
            return opt.fontMetrics.lineSpacing() * SARIBBONTOOLBUTTON_NOWORDWRAP_TEXT_FACTOR;
        }
    }
    //小按钮
    return opt.fontMetrics.lineSpacing() * SARIBBONTOOLBUTTON_SMALLBUTTON_TEXT_FACTOR;
}
```

也就是把原来的：
`return opt.fontMetrics.lineSpacing() * SARIBBONTOOLBUTTON_WORDWRAP_TEXT_FACTOR;`
变为：
`return opt.fontMetrics.lineSpacing() * SARIBBONTOOLBUTTON_WORDWRAP_TEXT_FACTOR + opt.fontMetrics.leading();`

增加了opt.fontMetrics.leading()行间距，看看有没有变化

**Comment by leonjang** [comment]
嗯嗯，我帮忙测试一下

**Comment by leonjang** [comment]
没有找到这个类calcTextDrawRectHeight， 这是在哪个分支的呀？

**Comment by czyt1988** [comment]
在SARibbonToolButton.cpp中

**Comment by leonjang** [comment]
测试好啦， 之前字体无法完全展示，现在可以啦

**Comment by czyt1988** [comment]
[42a4181](https://github.com/czyt1988/SARibbon/commit/42a4181dbad6fb8e5ddc4836a38ff72165a82b34)
