### ISSUE TITLE
2行的样式，可以添加pannel名称吗？

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#81]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/cca369ce-4479-400e-8f3f-f70f3a8275e1)
这个采用了2行的pannel样式，但是pannel的名称消失了， 好处是recent的箭头是在同一行。

三行的样式有pannel名称，但是箭头占了一段空间
![image](https://github.com/czyt1988/SARibbon/assets/33179543/5b5f411b-6e91-4426-b895-b9a50b83d12a)

请问楼主，可以有2行的pannel样式，箭头也是同一行，并且也包括pannel名称吗？ 如果需要改，应该改哪块代码呀？

**Comment by czyt1988** [comment]
2行office样式有pannel title，wps样式统一都没有pannel title
