### ISSUE TITLE
pannel 名称的间距是否可以调整

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#83]
楼主您好，请问一下
![image](https://github.com/czyt1988/SARibbon/assets/33179543/1fb376ef-c01a-475b-b361-fc4f3255798f)
toggle这个地方的底部的间距可以缩小吗？ 在哪个地方进行修改呀？我去试试

**Comment by czyt1988** [comment]
SARibbonPannel::pannelTitleHeight()决定了这个标题栏的高度
