### ISSUE TITLE
pannel中的图标可以居中显示吗

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#84]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/4f15f9fd-aaaf-486b-8d13-bb1d809341fd)
红框中的图标，在offciestyle下，无法居中展示

**Comment by czyt1988** [comment]
ribbon的图标都是统一左对齐，pannel相对category左对齐，action相对pannel左对齐

**Comment by leonjang** [comment]
明白，  在dev分支，这个问题似乎没有了， 就是有个间距的问题，  都写在issue #86了
