### ISSUE TITLE
图标大小不一致

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#85]
![img_v2_1d9cc5b8-dfbe-4dc8-b803-3eeec8622ddg](https://github.com/czyt1988/SARibbon/assets/33179543/5920eef2-c576-4499-8bd0-bf4202edc511)
在2k屏幕下，120缩放

**Comment by czyt1988** [comment]
这个图标受文字长度影响了，短文字的action生成的按钮宽度较小，所以图标就显得小了
我调整一下，在评估按钮大小时考虑到图标的长宽比，让图标占满

**Comment by czyt1988** [comment]
你可以拉取一下最新dev分支，修改了图标宽度的最小限制，保证最小宽度大于等于图标高度

**Comment by leonjang** [comment]
好的，感谢，我试一下

**Comment by leonjang** [comment]
测试成功， 没有问题了，但是还有一些新的问题， 都汇报在issue #86了
