### ISSUE TITLE
quickaccessbar的icon调整大小  +     最大化的时候间距变化了

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#86]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/4396fbc7-307e-4604-8316-5828052547aa)
红框处的icon变得很小， 应该是分辨率比较高；
请问楼主有没有办法手动调整一下大小，或者通过调高titlebar的高度， 把这块变高点。
应该改哪个地方呀？

**Comment by czyt1988** [comment]
这应该算是bug，我调整一下

**Comment by leonjang** [comment]
现在quickaccess的图标大小问题解决啦！  但是还有一个问题；

我在quickaccess左边加了一个titlename，  然后最大化的时候， 会多出来一个空间

最大化前：
![image](https://github.com/czyt1988/SARibbon/assets/33179543/641c457d-9f00-4a87-bd96-bf1492747e7b)
最大化后：

![image](https://github.com/czyt1988/SARibbon/assets/33179543/e92e64f5-e06c-464c-b3bb-963b7176ac2f)

**Comment by leonjang** [comment]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/417460f9-e1f9-46b3-b635-1d254540d797)
这里是一个icon + 一个名称

**Comment by leonjang** [comment]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/0547d62e-0cb7-4cab-8302-762416d174cd)

**Comment by leonjang** [comment]
应该是相同的问题，重绘的时候有点问题：

最大化前：
![image](https://github.com/czyt1988/SARibbon/assets/33179543/e53dc27b-172a-4547-ade7-ea3ba54af3ff)
最大化后：
![image](https://github.com/czyt1988/SARibbon/assets/33179543/2d040568-9ac6-443d-8c6c-75a74bf16030)

**Comment by leonjang** [comment]
我把titlename去掉，发现这里的quickaccess的图标大小在最大化前是有问题的。
最大化前这么小：
![image](https://github.com/czyt1988/SARibbon/assets/33179543/66b8800a-2496-4a17-9ed8-21e2de52c433)
最大化后变大了：
![image](https://github.com/czyt1988/SARibbon/assets/33179543/af0187ae-1b3a-4241-8989-3e18b99d606c)

**Comment by czyt1988** [comment]
重绘时机问题，尽量先确认父子关系再添加action
例如
new pannel后，先add进category再执行添加action的操作

如下面这个会在显示时没有刷新：
```cpp
    SARibbonPannel* pannel1 = new SARibbonPannel(("pannel 1"));
    SARibbonPannel* pannel2 = new SARibbonPannel(("pannel 2"));

    QAction* actionRemovePanne = createAction(tr("remove pannel"), ":/icon/icon/remove.svg");

    connect(actionRemovePanne, &QAction::triggered, this, [ page, pannel2 ]() { page->removePannel(pannel2); });
    pannel1->addLargeAction(actionRemovePanne);

    QAction* actionRemoveCategory = createAction(tr("remove this category"), ":/icon/icon/removePage.svg");

    connect(actionRemoveCategory, &QAction::triggered, this, [ this, page, actionRemoveCategory ]() {
        this->ribbonBar()->removeCategory(page);
        page->hide();
        page->deleteLater();
        actionRemoveCategory->setDisabled(true);
    });
    pannel2->addLargeAction(actionRemoveCategory);

    page->addPannel(pannel1);
    page->addPannel(pannel2);
```

但改为这样就好了：

```cpp
    SARibbonPannel* pannel1 = new SARibbonPannel(("pannel 1"));
    SARibbonPannel* pannel2 = new SARibbonPannel(("pannel 2"));

    page->addPannel(pannel1);
    page->addPannel(pannel2);

    QAction* actionRemovePanne = createAction(tr("remove pannel"), ":/icon/icon/remove.svg");

    connect(actionRemovePanne, &QAction::triggered, this, [ page, pannel2 ]() { page->removePannel(pannel2); });
    pannel1->addLargeAction(actionRemovePanne);

    QAction* actionRemoveCategory = createAction(tr("remove this category"), ":/icon/icon/removePage.svg");

    connect(actionRemoveCategory, &QAction::triggered, this, [ this, page, actionRemoveCategory ]() {
        this->ribbonBar()->removeCategory(page);
        page->hide();
        page->deleteLater();
        actionRemoveCategory->setDisabled(true);
    });
    pannel2->addLargeAction(actionRemoveCategory);
```

此问题正修复中

**Comment by czyt1988** [comment]
这个问题是否解决了
