### ISSUE TITLE
在第二个屏幕， 最大化的问题

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#87]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/f8ca53d9-f83a-48ea-84ee-29f1b02af1cb)
在第二个屏幕，最大化变成了 fullScreenWindow， 而不是maximumWindow了

**Comment by leonjang** [comment]
底边的任务栏看不见了

**Comment by leonjang** [comment]
是不是通过SAFramelessHelp去监听事件， 如果是第二个屏幕，就防止屏幕最大化

**Comment by czyt1988** [comment]
这个的确没有考虑过第二屏的问题，我准备把你提交的pr合并看看，frameless的问题还是交由第三方的frameless来解决

**Comment by leonjang** [comment]
这个问题，在最新的dev分支里居然不见了，不会在第二个屏幕直接变成全屏超过底下任务栏。
