### ISSUE TITLE
wps模式下正常窗口，标题栏无法拖动，上边框区域拉伸不太灵

### ISSUE THREAD

**Issue by HaojieTian** [czyt1988/SARibbon#9]
你好：
        我想使用wps模式，但wps模式下正常窗口不再是wps模式了，如图：
![2020-08-28_22-05-09](https://user-images.githubusercontent.com/49965646/91579916-e6780d80-e97e-11ea-9e65-07f88f17d0d5.png)
        修改resizeEvent()后是wps模式了，但标题栏却无法拖动窗口了(红色表示部分)，且上边框拉伸不咋灵了(橙色表示部分)。
![3](https://user-images.githubusercontent.com/49965646/91579847-ccd6c600-e97e-11ea-87c0-d71eb3dbaedd.png)
        看了事件传递，但不太明白RibbonBar上的标题栏和按钮上面的事件是如何传递给Frameless 标题栏的。
        请问还要修改哪里呀？谢谢！

**Comment by czyt1988** [comment]
//20200831
//tabBarWidth的宽度原来为endX - x;，现需要根据实际进行调整
//为了把tabbar没有tab的部分不占用，这里的宽度需要根据tab的size来进行设置，让tabbar的长度刚刚好，这样能让出
//mainwindow的空间，接受鼠标事件，从而实现拖动等操作，否则tabbar占用整个顶栏，鼠标无法点击到mainwindow
//计算tab所占用的宽度

一句话就是你更新一下最新版就好了，最新版改为非最大最小化时，wps模式会保持

最新修改如下：
```cpp
    case WpsLiteStyle:
    {
        resizeInWpsLiteStyle();
        return;

        break;
    }
```
`void SARibbonBar::resizeInWpsLiteStyle()`中需要修改
```cpp
int tabBarHight = validTitleBarHeight - 2;
    int tabBarWidth = endX - x;
    //20200831
    //tabBarWidth的宽度原来为endX - x;，现需要根据实际进行调整
    //为了把tabbar没有tab的部分不占用，这里的宽度需要根据tab的size来进行设置，让tabbar的长度刚刚好，这样能让出
    //mainwindow的空间，接受鼠标事件，从而实现拖动等操作，否则tabbar占用整个顶栏，鼠标无法点击到mainwindow
    //计算tab所占用的宽度
    int mintabBarWidth = calcMinTabBarWidth();

    if (mintabBarWidth < tabBarWidth) {
        tabBarWidth = mintabBarWidth;
    }
    y += 2;
    m_d->ribbonTabBar->setGeometry(x
        , y
        , tabBarWidth
        , tabBarHight);
```

当然和tabbar的addbar和removebar都要重新计算宽度，这里直接会调用resizeInWpsLiteStyle进行刷新。
具体见最新的master提交

**Comment by HaojieTian** [comment]
嗯，谢谢。


------------------&nbsp;Original&nbsp;------------------
