### ISSUE TITLE
在副屏中， 最大化窗口，会导致窗口显示异常

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#90]
dev 分支 & master 分支 都有这个问题，
在主屏幕中的最大化：
![image](https://github.com/czyt1988/SARibbon/assets/33179543/5d4ca6c2-692a-4195-8c12-0dafa1ce97aa)
在副屏中的最大化：
![image](https://github.com/czyt1988/SARibbon/assets/33179543/0dd2bcbc-dc63-4b7d-9a44-616368966b2d)

可以发现副屏中的任务栏被遮盖了， 这本来没什么大问题， 但是我们的项目中这会引发一个VTK闪烁的问题 : (   
求助楼主~！

**Comment by leonjang** [comment]
补充说明： 这种情况在下面的屏幕配置下可以稳定复现， 屏幕1是高分辨率4k & 150缩放， 屏幕2是1080 & 125缩放。 比较关键的是1080的屏幕2是主屏幕。 测试了很多下， 发现跟缩放关系不大， 跟分辨率关系比较大， 当主屏是低分辨率的时候，就会出现这个问题。

![img_v2_c10faa2c-c0c4-4002-93d8-0579c617621g](https://github.com/czyt1988/SARibbon/assets/33179543/cbdbaf68-507c-46e4-8e2a-48c7f91d3588)

![img_v2_935393cd-3bb6-4c5e-bdab-b66dfc05f52g](https://github.com/czyt1988/SARibbon/assets/33179543/d1fc34b5-736a-4710-a446-5134a9a7c90a)

**Comment by czyt1988** [comment]
引入frameless解决副屏问题，但主屏副屏缩放比例不一样会有显示异常问题还未解决

**Comment by gooker** [comment]
在副屏中， 最大化窗口，会导致窗口闪烁 解决了吗
