### ISSUE TITLE
在4k屏幕中， 缩放调整到250%， 会导致字体无法正常显示

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#91]
![image](https://github.com/czyt1988/SARibbon/assets/33179543/23dddbaf-3d10-42e7-8bf1-d1b2025c2da7)

**Comment by leonjang** [comment]
楼主好，在实际项目中， icon变得很小，但是字体是清晰的
![img_v2_ce9f98b4-8118-47cc-a391-b9b9a7c24dcg](https://github.com/czyt1988/SARibbon/assets/33179543/4e0b9e56-90a6-45c8-8331-fb09515edee6)

**Comment by leonjang** [comment]
类似的问题，在另一台机器上：
![image](https://github.com/czyt1988/SARibbon/assets/33179543/e57a88cf-fb90-458c-91ae-8c5a8346734d)


以上采用的都是dev环境

**Comment by czyt1988** [comment]
> 楼主好，在实际项目中， icon变得很小，但是字体是清晰的 ![image](https://user-images.githubusercontent.com/33179543/269135029-1583d39b-6746-46c5-8ddb-16f32d1b65a6.png)

这个是在什么屏幕什么缩放比例下的？
字体变大会挤压掉图标显示空间，而ribbonbar的高度是固定像素所以导致这个问题，我这边没有4k屏很多测试无法做，这个问题我这段时间专门解决一下

**Comment by leonjang** [comment]
楼主您好，是在4k屏幕下， 缩放250的情况下出现的。感谢支持~ 谢谢您！

**Comment by czyt1988** [comment]
你好，麻烦试一下这个分支：[frameless](https://github.com/czyt1988/SARibbon/tree/frameless)，这个分支我把第三方库frameless集成进来了，目前只支持qmake，还没处理cmake

另外，你改变屏幕缩放比例后，有没有重新启动程序，因为我没做监控屏幕缩放比例事件的捕获，不会自动更新，但下次打开程序应该是能适应的

还有在main函数之前是否调用了`QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);`

```cpp
int main(int argc, char* argv[])
{
#if (QT_VERSION >= QT_VERSION_CHECK(5, 6, 0))
    QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif
    QApplication a(argc, argv);
  ......
}
```

**Comment by gooker** [comment]
这个问题是qt对高dpi支持的不好,和saribbon程序关系不大,我双屏4k笔记本 150% dpi正常.
