### ISSUE TITLE
1080p

### ISSUE THREAD

**Issue by leonjang** [czyt1988/SARibbon#92]

**Comment by leonjang** [comment]
楼主您好，
![image](https://github.com/czyt1988/SARibbon/assets/33179543/839a3104-4b74-4e79-894a-c1f3ce11bb6e)
![image](https://github.com/czyt1988/SARibbon/assets/33179543/b25af37d-c4f5-4110-90c2-a38b311cfee8)

以上是未窗口最大化前，以下是窗口最大化后，会恢复正常
![image](https://github.com/czyt1988/SARibbon/assets/33179543/bc275ab9-d53d-4584-92a0-2af1fd750138)

使用的是dev分支

**Comment by czyt1988** [comment]
你好能否留下联系方式方便沟通，我这边没有高分屏和多屏，希望你协助修复高分屏的问题
我的qq：511508214

**Comment by leonjang** [comment]
好的，谢谢楼主，已经加您了。
