### ISSUE TITLE
linux下无法将对话框拖出显示器窗口

### ISSUE THREAD

**Issue by ColaWithBeijingroastduck** [czyt1988/SARibbon#93]
[v0.7.0](https://github.com/czyt1988/SARibbon/releases/tag/v0.7.0)

Ubuntu和Red Hat都存在这个现象，windows下没有这个问题。

**Comment by czyt1988** [comment]
你好，你试试dev分支是否可以解决这个问题，dev分支将是1.0版本，为了解决linux和苹果相关问题的
