### ISSUE TITLE
Unable to compile with qmake

### ISSUE THREAD

**Issue by yanis60** [czyt1988/SARibbon#94]
Here is what i'm getting when i compile this project with Qt 5.15.0
![image](https://github.com/czyt1988/SARibbon/assets/30592254/d9c528dd-502e-4eb2-9d43-d6f91f43ba0d)

**Comment by czyt1988** [comment]
These macros are defined in `windows.h`
Look at line 82 under  `framelessHelper/core/framelesshelper_windows.h` 
Whether to activate `#include <windows.h>`  in your compiler
![image](https://github.com/czyt1988/SARibbon/assets/7260393/86cd8f97-de2e-4f0d-9182-195f50f2449d)

**Comment by yanis60** [comment]
i'm using mingw as a compiler

**Comment by czyt1988** [comment]
Compilation errors do occur when using Mingw. I have reported this problem to the author of the frameless library

**Comment by yanis60** [comment]
yes it fixed it, thank you
