### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by programClown** [czyt1988/SARibbon#95]
Hi，czyt1988，

目前编译Qt5.15 msvc版本没问题，但是5.12 msvc/mingw都编译不过，问题是frameless库造成的，感觉目前5.12还是有一定的生产力的，可修复一下，谢谢

**Comment by czyt1988** [comment]
mingw的确会发生错误，我已经把此问题反馈给frameless库的作者
5.12的msvc编译不过应该是没打开c++17的支持，由于frameless必须c++17，因此无法使用太低版本的qt，不过建议还是使用5.14以上，否则高分屏会有bug

**Comment by programClown** [comment]
SARibbon是已经开了CPP17选项的，而且5.12编译工具链是VS2019，我想应该不是CPP17的问题，是不是哪里未配置正确

**Comment by czyt1988** [comment]
> SARibbon是已经开了CPP17选项的，而且5.12编译工具链是VS2019，我想应该不是CPP17的问题，是不是哪里未配置正确

5.12报的编译错误是什么？

**Comment by programClown** [comment]
![image](https://github.com/czyt1988/SARibbon/assets/8369309/e0385ea4-9020-4d91-86ee-ec3d01c5d788)

这只是一处，改完还有有别的错误，感觉FramelessHelper不支持Qt5.12

**Comment by czyt1988** [comment]
mingw的编译问题已经修复，拉取最新的master分支即可，qt5.12编译问题我正和frameless作者联系中

**Comment by czyt1988** [comment]
> > SARibbon是已经开了CPP17选项的，而且5.12编译工具链是VS2019，我想应该不是CPP17的问题，是不是哪里未配置正确
> 
> 5.12报的编译错误是什么？

frameless的确无法在5.12下编译，最低要求5.14

**Comment by programClown** [comment]
frameless用了一些不兼容的api，比如qmlRegisterAnonymousType，兼容到5.12还是有意义的

**Comment by czyt1988** [comment]
> frameless用了一些不兼容的api，比如qmlRegisterAnonymousType，兼容到5.12还是有意义的

做了低版本兼容，在使用低版本的qt时，不会使用frameless库，但目前自己实现的frameless实现效果不好，后面我会找一个比较折中的frameless方案
