### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by leexfs** [czyt1988/SARibbon#96]
新提供的widget例子运行不了报错，麻烦提供一下cmake能运行版本，并把作者的环境配置列一下，我按照你的配置运行，困扰好几天了，谢谢

**Comment by czyt1988** [comment]
widget例子的cmake已添加，你拉取最新的master分支即可

**Comment by czyt1988** [comment]
最低qt版本要求是5.14

**Comment by gooker** [comment]
> 最低qt版本要求是5.14

5.12 有没有办法适配一下

**Comment by leexfs** [comment]
感谢！

**Comment by czyt1988** [comment]
> > 最低qt版本要求是5.14
> 
> 5.12 有没有办法适配一下

这个受限于frameless库，目前我在看这个库如何适配到qt5.12，如果可以我提交个pr到frameless库去

**Comment by gooker** [comment]
> > > 最低qt版本要求是5.14
> > 
> > 
> > 5.12 有没有办法适配一下
> 
> 这个受限于frameless库，目前我在看这个库如何适配到qt5.12，如果可以我提交个pr到frameless库去

期待支持

**Comment by czyt1988** [comment]
> > 最低qt版本要求是5.14
> 
> 5.12 有没有办法适配一下

做了低版本兼容，在使用低版本的qt时，不会使用frameless库，但目前自己实现的frameless实现效果不好，后面我会找一个比较折中的frameless方案
