### ISSUE TITLE
原生視窗切換功能失效

### ISSUE THREAD

**Issue by timpc0526** [czyt1988/SARibbon#98]
目前已經測試過純Qt擁有此功能，加入SARibbon後此功能失效(將視窗拖拉到螢幕邊緣應該跳出類似docking layout的功能)

**Comment by czyt1988** [comment]
Qt5.14以上版本支持原生的贴边效果，SARibbon引入了[framelesshelper库](https://github.com/wangwenx190/framelesshelper)实现无边框窗体，但此库最低Qt版本要5.14以上，如果你编译出来的SARibbon无法实现原生贴边效果，说明低于Qt5.14

**Comment by timpc0526** [comment]
目前使用Qt版本為Qt5.15.2，因該是高於Qt5.14版本的，問題變複雜了...
嘗試運行您的Demo也同樣無法支持原生貼邊，但我有試著重新建立新的空白Qt專案卻支持原生貼邊效果，
所以才會覺得很困惑，仍然非常感謝您的回覆~

**Comment by czyt1988** [comment]
如果用5.15，那是支持这个效果的，如下图所示

![SARibbonBar-docking-screen-side](https://github.com/czyt1988/SARibbon/assets/7260393/e2166838-97f1-48f7-b488-081face91f06)

你用的是最新版吗？你可以确认一下是否使用了src/3rdparty/framelesshelper库，SARibbon的无边框方案主要通过framelesshelper库来实现，如果用了也没有效果，那麻烦看看是什么操作系统，我看看是否有不一样的操作

**Comment by timpc0526** [comment]
目前系統為 MSVC 2019 + Qt 5.15.2，會先使用Qt Creator編譯成DLL LIB的形式進行叫用
已發現之前是沒有使用到src/3rdparty/framelesshelper庫，然而我嘗試編譯此庫時，
會發生一長串LNK2019, LNK2001等無法解析外部符號，
有特別在qmake加入C++17，
至少已經找到問題點，會再嘗試看看編譯

**Comment by czyt1988** [comment]
> 目前系統為 MSVC 2019 + Qt 5.15.2，會先使用Qt Creator編譯成DLL LIB的形式進行叫用 已發現之前是沒有使用到src/3rdparty/framelesshelper庫，然而我嘗試編譯此庫時， 會發生一長串LNK2019, LNK2001等無法解析外部符號， 有特別在qmake加入C++17， 至少已經找到問題點，會再嘗試看看編譯

最近的frameless库更新后会qmake失败，你可以使用cmake来编译，cmake是可以编译的，目前qmake的问题我正联系frameless的作者进行修改

**Comment by timpc0526** [comment]
非常感謝您，已經成功使用cmake編譯，並且demo也可以實現原生貼邊效果，
然而在要移植進VS專案中出現以下錯誤，想請問是不是有檔案沒有加入
![errorCode](https://github.com/czyt1988/SARibbon/assets/68679458/9a6adf58-76f1-4b03-819a-d760c179c5a6)

**Comment by czyt1988** [comment]
> 非常感謝您，已經成功使用cmake編譯，並且demo也可以實現原生貼邊效果， 然而在要移植進VS專案中出現以下錯誤，想請問是不是有檔案沒有加入 ![errorCode](https://private-user-images.githubusercontent.com/68679458/285424895-9a6adf58-76f1-4b03-819a-d760c179c5a6.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDIzNDMsIm5iZiI6MTcwMTI0MjA0MywicGF0aCI6Ii82ODY3OTQ1OC8yODU0MjQ4OTUtOWE2YWRmNTgtNzZmMS00YjAzLTgxOWEtZDc2MGMxNzljNWE2LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA3MTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMmQ4MDVlNzNmOThiYzQ4NmQ5NmYzMjkxZTg3ZTUyMGU1NWJlYTFhYTEzMWQ4MDYzNjA3MmFlN2Y3MzAwZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4xzBpa4whlnJ_xOBkBLaxh8KfXSs_YENzT7xh3UVRqg)

这个问题像是qmake执行失败出现的，你可以试着拉取最新的dev分支，使用cmake后，install，通过:
```cmake
# 定义SARibbonBar的搜索位置，就是你make install的位置
set(SARibbonBar_DIR "${CMAKE_INSTALL_PREFIX}/../SARibbon/lib/cmake")

# 3rdparty - SARibbon
find_package(SARibbonBar)
include_directories(${SARibbonBar_INCLUDE_DIR})
```

**Comment by timpc0526** [comment]
請問是要將上面那段加入CMakeList.txt中(加入在哪個位置)，再進行cmake以及Install嗎?

**Comment by czyt1988** [comment]
我看你是用vs自己建立的工程，你用vs引入lib后需要做以下事情：
1、把include路径加好，include路径包括下面这三个：
![image](https://github.com/czyt1988/SARibbon/assets/7260393/72e09276-375e-4d68-9c9b-2ce3fdb0f495)
2、定义好宏,下面这两个宏必须添加：
```
SARIBBON_USE_3RDPARTY_FRAMELESSHELPER=1
FRAMELESSHELPER_FEATURE_static_build=-1
```

**Comment by timpc0526** [comment]
非常感謝大大這麼熱心以及有耐心的回覆 終於可以用了 這裡幫之後使用的人寫個成功使用的流程
這是使用VS建立Qt專案，將SARibbon引入使用
環境 Qt5.15.2 + VS2019 (qtCreator編譯Qt及VS版本要記得與VS專案相同)
1. 使用qtCreator對SARibbon.pro進行編譯，qmake額外引數加入CONFIG+=C++17，將shadow build關閉
2. 編譯後自己指定路徑新增兩個資料夾 include資料夾將src/SARibbon整個資料夾放入 lib資料夾將生成的lib dll放入
3. 將dll檔放置在VS專案資料夾中
4. VS C/C++ 一般/其他include目錄 加入
-   yourPath\include\SARibbon
-   yourPath\include\SARibbon\3rdparty\framelesshelper\include
-   yourPath\include\SARibbon\3rdparty\framelesshelper\qmake\inc\core
5. VS 連結器 其他程式庫目錄 加入
-   yourPath\lib
6. VS 連結器 輸入 其他相依性 加入
-   Debug -> SARibbonBar.lib
-   Release -> SARibbonBard.lib
7. 即可成功運行 (有錯再請各位修正)
